### ISSUE TITLE
Sleuth and Reactor Schedulers

### ISSUE THREAD

**Issue by matthewjmason** [spring-cloud/spring-cloud-sleuth#1014]
I'm having issues with my Reactor scheduling and concurrency after including spring-cloud-starter-sleuth from BOM `org.springframework.cloud:spring-cloud-sleuth:2.0.0.RELEASE`. I am using `io.projectreactor:reactor-bom:Bismuth-SR10`.

For my test case, I have the following Flux:
```java
public void restEndpoint() {
        Flux.range(1, 10)
                .flatMap(val -> serviceLayer(val).publishOn(Schedulers.elastic()))
                .blockLast();
}

public Mono<Integer> serviceLayer(Integer val) {
        return Mono.fromCallable(() -> {
            Thread.sleep(1000);

            LOG.info(Thread.currentThread().getName() + " " + val);

            return val;
        });
}
```

The purpose of this is to take a series of events and publish them in parallel. When running without the sleuth dependency, the output is:
```
[INFO ] 2018-06-21 12:02:31 [http-nio-8080-exec-2]: Starting
[INFO ] 2018-06-21 12:02:32 [elastic-2]: elastic-2 1
[INFO ] 2018-06-21 12:02:32 [elastic-6]: elastic-6 5
[INFO ] 2018-06-21 12:02:32 [elastic-7]: elastic-7 6
[INFO ] 2018-06-21 12:02:32 [elastic-4]: elastic-4 3
[INFO ] 2018-06-21 12:02:32 [elastic-5]: elastic-5 4
[INFO ] 2018-06-21 12:02:32 [elastic-11]: elastic-11 10
[INFO ] 2018-06-21 12:02:32 [elastic-9]: elastic-9 8
[INFO ] 2018-06-21 12:02:32 [elastic-8]: elastic-8 7
[INFO ] 2018-06-21 12:02:32 [elastic-10]: elastic-10 9
[INFO ] 2018-06-21 12:02:32 [elastic-3]: elastic-3 2
[INFO ] 2018-06-21 12:02:32 [http-nio-8080-exec-2]: Finished in 1059
```

However, when I include compile('org.springframework.cloud:spring-cloud-starter-sleuth') in my gradle dependencies, the output is:
```
[INFO ] 2018-06-21 12:06:23 [http-nio-8080-exec-1]: Starting
[INFO ] 2018-06-21 12:06:24 [http-nio-8080-exec-1]: http-nio-8080-exec-1 1
[INFO ] 2018-06-21 12:06:25 [http-nio-8080-exec-1]: http-nio-8080-exec-1 2
[INFO ] 2018-06-21 12:06:26 [http-nio-8080-exec-1]: http-nio-8080-exec-1 3
[INFO ] 2018-06-21 12:06:27 [http-nio-8080-exec-1]: http-nio-8080-exec-1 4
[INFO ] 2018-06-21 12:06:28 [http-nio-8080-exec-1]: http-nio-8080-exec-1 5
[INFO ] 2018-06-21 12:06:29 [http-nio-8080-exec-1]: http-nio-8080-exec-1 6
[INFO ] 2018-06-21 12:06:30 [http-nio-8080-exec-1]: http-nio-8080-exec-1 7
[INFO ] 2018-06-21 12:06:31 [http-nio-8080-exec-1]: http-nio-8080-exec-1 8
[INFO ] 2018-06-21 12:06:32 [http-nio-8080-exec-1]: http-nio-8080-exec-1 9
[INFO ] 2018-06-21 12:06:33 [http-nio-8080-exec-1]: http-nio-8080-exec-1 10
[INFO ] 2018-06-21 12:06:33 [http-nio-8080-exec-1]: Finished in 10087
```
I am flexible on the way the Flux is written/structured but I am unable to figure out how write this such that I am able to achieve the concurrency from the first output with Sleuth.

**Comment by matthewjmason** [comment]
For some additional info, I was able to restructure the flow as:
```java
    public Mono<Integer> printIt(Integer val) {
        return Mono.just(val)
                .publishOn(Schedulers.elastic())
                .flatMap((vl) -> {
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        LOG.error("Error", e);
                    }

                    LOG.info(Thread.currentThread().getName() + " " + val);

                    return Mono.just(val);
        });
    }
});
```
and this seems to publish in parallel with Sleuth. The issue might be with Mono.fromCallable but that's speculation on my part.

**Comment by simonbasle** [comment]
@matthewjmason you are right, the root cause is the use of `Mono.fromCallable()` together with `publishOn`. I actually think you probably needed `subscribeOn` instead, here's why:

`publishOn` only changes threads once the data has been generated and emitted upstream. It means that normally the `Mono.fromCallable` should have been executed in the Thread it is subscribed from (the request IO thread) and _then_ its value would be handed over to the `elastic` thread.

But `publishOn` also optimizes for `Publisher` sources that are also `Callable`: it avoids a subscribe-and-request overhead by directly calling `Callable#call` from the `Thread` it was supposed to hand over (here the `elastic` thread).

When you add Sleuth, it decorates each step of that reactive chain with something that happens to **not** be a `Callable`, and you revert back to the "unoptimized" version.

In your case however, the unoptimized version is very undesirable because it ends up `sleep`ing the IO threads. What you want is isolate the blocking behavior in an `elastic` thread, and the correct fool-proof way of doing that is to use `subscribeOn`.

`publishOn` happened to work thanks to the optimization, which ends up approximating a `subscribeOn` for `Mono.fromCallable`, but Sleuth has the side effect of deoptimizing here and it exposes the mistake.

**Comment by marcingrzejszczak** [comment]
Thanks @simonbasle for this great response. You're the best!
