### ISSUE TITLE
how can we override traceId in sleuth version greater than 2.0.0 ?

### ISSUE THREAD

**Issue by shaileshpratapsingh** [spring-cloud/spring-cloud-sleuth#1106]
There is one blog https://blog.michaelstrasser.com/2017/07/using-sleuth-trace-id/#inserting-the-sleuth-trace-id. This explains how to customize traceid before brave library is being implemented. I'm trying to customize traceId in latest spring sleuth(<2.0.0). Please help

**Comment by shaileshpratapsingh** [comment]
Requirement: Instead of randomly generated traceId and SpanId, we need to inject our custom traceId(which will be combination of different available Ids)

**Comment by marcingrzejszczak** [comment]
The ID needs to be a 64bit or 128 bit number. You can't override it. However, you can use the propagation keys (https://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#prefixed-fields) to propagate the id that in your company is the trace id, and you can modify the MDC to have that value injected.

**Comment by adriancole** [comment]
in super advanced case you can write a FinishedSpanHandler to map normal
ids to custom format to a custom library which isnt normal hex.

however you cant get brave to generate span ids that are different size
than 64bit.

**Comment by shaileshpratapsingh** [comment]
thanks

**Comment by amandasantanati** [comment]
So is there no way to override traceId? 
My requirement is that the traceId comes from other service and it is passed agnostic by a kafka message header. I can retrieve this header from the message but I can't override the traceId. I am using @KafkaListener to receive the kafka message and it seems that it can't smoothly decode (parse) the X-B3-TraceId and the X-B3-SpanId as it gives me some errors as soon as the service consumes the message.
I am aware of [this issue](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1001) but it seems that it's not working as expected for me.
I have been looking through documentation and internet code examples but none could provide me any help. 
Could somebody tell me what should I do to accomplish it?

**Comment by prasad-1210** [comment]
Hello, I am trying to override Trace ID. Here is my usecase: 

i would like to use my X-Request-ID generated at Nginx Ingress controller on my Kubernetes cluster as X-B3-Trace-ID so that i can trace since request entered Cluster rather than from tomcat using same ID on my ELK Stack instead of multiple IDs for different layers.

**Comment by neiser** [comment]
@marcingrzejszczak I actually do have a use case where adding a new header doesn't help:

In our project, we have a few different cluster environments, all completely independent of each other. However, people within the project usually tell you the trace id when they encounter a problem, but not the cluster environment it was generated from. So usually my first follow-up question to them is "Which environment?". Otherwise I can't search for logs and investigate the issue. This could be solved if we generated trace ids a little bit less random, for example in one environment, each trace id starts with `0`, and the other environment, each trace id starts with `1`, and so on. This way I could tell where trace id came from without asking. To make it even worse, sometimes people tell you the wrong environment, because they're confused.

You may ask now why do we have so many environments, but well, that's another story and this can't be changed, but maybe trace ids can. If you agree that this is a valid use case for "influencing" the trace id generation, and if I can support you in implementing something, let me know.

**Comment by adriancole** [comment]
@neiser the approach you discuss is very edge case. I would recommend putting a filter in front of your service if you must do this. use b3 single format and decide however you want, as long as the encoding is valid. ex b3: traceid-spanid where both can be same if 64-bit (16 character) https://github.com/openzipkin/b3-propagation/#single-header

ex one environment leads with all zeros

"b3", "0000000000000000e457b5a2e4d86bd1-e457b5a2e4d86bd1"

ex another environment leads with 1 then all zeros

"b3", "1000000000000000e457b5a2e4d86bd1-e457b5a2e4d86bd1"

this is not me recommending this approach, just for whatever reason you can't use normal propagated "env", "0" extra field, this is better than changing the project to do something weird.

**Comment by adriancole** [comment]
actually all leading zeros would be a bad idea as that would be undifferentiated from a 64bit trace ID.. fixed my comment

**Comment by antonalechnovic** [comment]
Think use case is totally justified, we have loadbalancer which generates traceid, should be able to tell zipkins what to use for trace id? ATM we only have a running POC with zipkins and we have our own libs with filters which capture traceIds and put them into MDC. Sounds like we will have some trouble with this.

**Comment by adriancole** [comment]
It is certainly best to change your LB if possible, to forward a valid B3 header. As it seems you can't..

You can take a look at this and copy/paste the solution into whatever version of Sleuth you want as the code needed is compatible with a long time back. https://github.com/openzipkin/brave/pull/1144

In sleuth 2.2, you would do.. 
```java
@Bean ExtraFieldPropagation.Factory customPropagationFactory() {
  return ExtraFieldPropagation.newFactory(
      CustomTraceIdPropagation.create(B3Propagation.FACTORY, "my_trace_id"));
}
```

In Sleuth 3.0, this
```java
@Bean BaggagePropagation.Factory customPropagationFactory() {
  return BaggagePropagation.newFactory(
      CustomTraceIdPropagation.create(B3Propagation.FACTORY, "my_trace_id"));
}
```

**Comment by durga729** [comment]
> The ID needs to be a 64bit or 128 bit number. You can't override it. However, you can use the propagation keys (https://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#prefixed-fields) to propagate the id that in your company is the trace id, and you can modify the MDC to have that value injected.

Can to tell how to use propagation key??give some examples
