### ISSUE TITLE
Sleuth 2.0 not reading the X-B3-TraceId header

### ISSUE THREAD

**Issue by jm-ck** [spring-cloud/spring-cloud-sleuth#1116]
After migrating Spring Boot from 1.5 to 2.0 and Sleuth from Edgware (1.3.0.RELEASE) to Finchley (2.0.0.RELEASE) the `X-B3-TraceId` HTTP Header is not interpreted by Sleuth. Sleuth assigns its own `traceId`, not the one from the header.

In `1.3.0.RELEASE` when HTTP request came with `X-B3-TraceId` header set to valid value (e.g. `1234567890abcdef`), the `traceId` was properly set and logged. No `X-B3-SpanId` was required.

In `2.0.0.RELEASE` when HTTP request comes with ONLY `X-B3-TraceId` set, the `traceId` is not set from the header but it's randomly generated. `traceId` however is set when both `X-B3-TraceId` and `X-B3-SpanId` HTTP Headers are present in the request. In this case both, `traceId` and `spanId` are set to the values from headers.

Is it an intended behavior? I need just to read `X-B3-TraceId`, `spanId` should be in this case generated and `traceId` taken from the header.

On `2.0.2.RELEASE` behavior is the same.

**Comment by marcingrzejszczak** [comment]
I don't really understand what you're saying. Spring Cloud Sleuth DOES use the `X-B3-TraceId` so I don't really know what your problem is. Can you replicate this issue in some sort of a sample?

**Comment by devinsba** [comment]
@jm-ck please correct me if I am wrong: You are saying that when you pass ONLY the `x-b3-traceid` header the value is not used, and that when you pass both `x-b3-traceid` and `x-b3-spanid` it is?

This is because passing only the trace ID is against the B3 specification. It may have worked in the past but now the implementation uses the official Zipkin library.

The specification relevant to your issue is here: https://github.com/openzipkin/b3-propagation#http-encodings 

Notice that the `x-b3-spanid` header is required

**Comment by jm-ck** [comment]
yes, this is what I meant. 

This clarifies the issue as this is expected behavior.

**Comment by srkankit** [comment]
yes i am also facing same issue, 
Even though we are sending "X-B3-TraceId" header, Sleuth will ignore present "X-B3-TraceId" header and convert "X-B3-TraceId" to all lower case and then add new "X-B3-TraceId" header.

Now when I am seeing 2 headers X-B3-TraceId and x-b3-traceid

**Comment by mariuswang007** [comment]
see the answer what I answered:
https://stackoverflow.com/a/70285596/10472281
