### ISSUE TITLE
Manually created load-balanced Feign Clients - Sleuth Instrumentation

### ISSUE THREAD

**Issue by tf-haotri-pham** [spring-cloud/spring-cloud-sleuth#1125]
Hi,
I have a Spring Boot 1.5.17 application that also includes the **spring-cloud-starter-zipkin** for trace ID generation. The application further uses Feign for any outbound REST calls, however the [Feign clients are created manually](https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-feign.html#_creating_feign_clients_manually) rather than via _@FeignClient_ annotation. Ribbon is included and I build the Feign clients with target URL as 
```java
Feign.builder()... .target(MyFeignClient.class, "http://my-service");
```
for which I have _my-service.ribbon.listOfServers_ set in my _application.properties_ file.

I have observed that the REST calls via the manually created (Ribbon load-balanced) Feign clients **do not include the trace information HTTP headers** (such as _x-b3-tracid_, etc.) and so I looked at the instrumentation config beans under [TraceFeignClientAutoConfiguration.java](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClientAutoConfiguration.java) to find out what I would need to do additionally for such manually created clients.

During debugging, I could however see that [TraceFeignAspect.java](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignAspect.java) does wrap the instantiated feign clients in respective _TraceLoadBalancerFeignClient_ or _TraceFeignClient_ instances, but these are never invoked ([code line 55](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3c25fc1a11b8d39e15bbb5c12b1225db582e72df/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignAspect.java#L55)):
```java
if (bean != wrappedBean) {
    return executeTraceFeignClient(bean, pjp);
}
```

I wanted to ask, if the line was meant to be
```java
return executeTraceFeignClient(wrappedBean, pjp);
```
(which I tried during debugging and resulted in the outgoing REST calls containing the trace information HTTP headers) or if not, whether there is an elegant way for me to add sleuth instrumentation to manually created load-balanced Feign clients?

P.S.: I did try the [OkHttpClient workaround](https://github.com/spring-cloud/spring-cloud-sleuth/issues/594), however that could not resolve the "my-service" named target URL.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by luryson** [comment]
Same question. I think `wrappedBean` should be passed, otherwise `tracing` will stop here.

**Comment by marcingrzejszczak** [comment]
Can you create a test that's failing and then implement a fix?

**Comment by luryson** [comment]
@marcingrzejszczak ok , but it'll take some time.

**Comment by colejnic** [comment]
@marcingrzejszczak I believe the new failing tests I added here explain the issue better. I don't have a solution, but they better expose the problem at least.
https://github.com/spring-cloud/spring-cloud-sleuth/compare/master...colejnic:issue_1125_tests?expand=1

**Comment by marcingrzejszczak** [comment]
Hey @colejnic I'm trying to work on the issue and I'm looking at the tests. In the Y case I can see that you're returning a fake response without actually calling a client.

```java

class MyClient extends LoadBalancerFeignClient {

	public MyClient(Client delegate, CachingSpringLoadBalancerFactory lbClientFactory,
			SpringClientFactory clientFactory) {
		super(delegate, lbClientFactory, clientFactory);
	}

	boolean wasCalled;

	@Override
	public Response execute(Request request, Request.Options options) throws IOException {
		this.wasCalled = true;
		return Response.builder().body("foo", Charset.forName("UTF-8"))
				.request(Request.create(Request.HttpMethod.POST, "/foo", new HashMap<>(), Request.Body.empty()))
				.headers(new HashMap<>()).status(200).build();
	}

	boolean wasCalled() {
		return this.wasCalled;
	}

}
```

I guess we shouldn't expect that request to be instrumented since, well, there is no request?

**Comment by marcingrzejszczak** [comment]
BTW 2, even if you remove Sleuth `then(this.myClient.wasCalled()).isTrue();` will not be true due to how `org.springframework.cloud.openfeign.FeignClientFactoryBean.java` works:

```java
Client client = getOptional(context, Client.class);
		if (client != null) {
			if (client instanceof LoadBalancerFeignClient) {
				// not load balancing because we have a url,
				// but ribbon is on the classpath, so unwrap
				client = ((LoadBalancerFeignClient) client).getDelegate();
			}
			builder.client(client);
		}
```

**Comment by colejnic** [comment]
@marcingrzejszczak I'm not sure I'm fully understanding, but unfortunately we may be seeing different things.. When I run IssueYTests, myClient.wasCalled is true. The assertions that fail are the spans checks. I added an additional test to my PR, Z: it's a more basic Y in a sense.

Both Y and Z do not use the @EnableFeignClients annotation, and instead create the MyNameRemote bean manually with the Feign.builder(). I'm not seeing FeignClientFactoryBean.getTarget being hit in those test cases (I'm not overly familiar with the library code, but my hunch is that is because I'm not creating MyNameRemote bean via the EnableFeignClients annotation; also just adding that creating MyNameRemote via the Feign.builder() is a documented way of creating those in the spring docs/it's not a hack).

However, both the Client beans are created 'normally'.
Y and Z show that creating the MyNameRemote bean, not using the EnableFeignClients don't work properly in regards to sleuth tracing.

I wasn't clear about Y originally, and I couldn't find an exact explanation either, but hopefully that makes more clear what Y (and Z) are trying to expose.

Let me know if you'd like me to clarify anything!

**Comment by marcingrzejszczak** [comment]
I copied your tests to my codebase and that's what i got. Can you create a sample that replicates this?

**Comment by colejnic** [comment]
@marcingrzejszczak I checked out master, made my branch, and added the test cases. Are you working off a different branch that I should be using as well?

**Comment by colejnic** [comment]
@marcingrzejszczak I see I accidentally left my sysout in Y and Z; just to confirm, you are not seeing 'this.myclient.wascalled: true' get printed? That is false for you?

**Comment by marcingrzejszczak** [comment]
I was working from 2.1.x afair. Can you file a pr with the failing test case to the 2.1.x branch?

**Comment by colejnic** [comment]
@marcingrzejszczak I opened a draft (not meant for merge) here: https://github.com/spring-cloud/spring-cloud-sleuth/pull/1490

That PR also contains a 'hacky fix' for the issues with sub-classing LoadBalancerFeignClient. With that 'fix', X and Y both pass/work as I would expect. Test Z still fails with or without it (hindsight I don't think I should have added Z, but I left it still in this PR).

If the 'fix' to TraceFeignObjectWrapper is removed, then tests in X and Y fail again like originally.

Let me know if you'd like to see something different

**Comment by BediarSofiane** [comment]
Hello,
I am facing the exact same issue with the sleuth-core version 1.3.5 (spring boot 1.5.22). I'm trying to understand the algorithm of wrapping the LoadBalancerFeignClient into a TraceLoadBlaancerFeignClient (and thus the delegate apacheHttpClient into a TraceFeignCliant).the wrapping algorithm seems very clear in the method wrap() of classs TraceFeignObjectWrapper.java. However i don't really understand why 
the wrappedBean is never used within the TraceFeignAspect.java. shouldn't it be used within the if statement when the bean and the wrapped bean are not the same instance (instead of using the bean)? In other words shouldn't the following piece of code:`if(bean != wrappedBean){return executeTraceFeignClient(bean,pjp);}` 
be replaced by: `if(bean != wrappedBean){return executeTraceFeignClient(wrappedBean,pjp);}`
I'm sure that there is a reason to why it has been done this way. But i don't get the point of it. Can you please explain what the algorithm is doing in the method feignClientWasCalled() please?
My second question concerns the version 1.3.5 of sleuth-core. once the fix is decided, will it be integrated to this version too? or only the 2.1.*?
Thank you!

**Comment by marcingrzejszczak** [comment]
It will be only integrated for 2.1.x and 2.2.x. 1.3.x is not maintained.

**Comment by BediarSofiane** [comment]
Thank you @marcingrzejszczak . Do you have an idea when will that be released?
What about my first question though ?

**Comment by marcingrzejszczak** [comment]
You have all the dates here https://github.com/spring-cloud/spring-cloud-release/milestones

I don't really understand your question.

**Comment by BediarSofiane** [comment]
My question briefly: what's the point of the if statement: `if(bean != wrappedBean){return executeTraceFeignClient(bean,pjp);}` in class TraceFeignAspect.feignClientWasCalled() ?

**Comment by marcingrzejszczak** [comment]
If the bean hasn't already been instrumented we instrument it, otherwise we continue

**Comment by luryson** [comment]
Still don't understand this piece of code `if(bean != wrappedBean){return executeTraceFeignClient(bean,pjp);}`. The wrapped `LazyTracingFeignClient` has never been called, then why do we wrap it ? 
![image](https://user-images.githubusercontent.com/7643503/71516440-fa490c80-28e3-11ea-9fac-488155f34844.png)

**Comment by BediarSofiane** [comment]
As @luryson said, the instumented bean (wrappedBean) is created but never used. That's why we don't get the point of that piece of code. @marcingrzejszczak can you please be more specific in the explanation? @colejnic maybe you have an idea on how that piece of code is working. I really don't get the point !

**Comment by marcingrzejszczak** [comment]
I don't understand which problem are we trying to solve? The issue is closed, the pull request has been merged.

> As @luryson said, the instumented bean (wrappedBean) is created but never used. That's why we don't get the point of that piece of code.

If you don't have a custom `TracedLoadBalancerClient` we have wrapped its client into a trace. The aspect will try to wrap it and since it's already a `TLBC` we will just return that instance and proceed with the code execution.

If you have a custom `LoadBalancerFeignClient`, we will see that it's not a `TLBC` so we will wrap your delegate in a trace representation and return a `TLBC`.

If you don't have ribbon on the classpath we need to use reflection to retrieve the delegate cause there's no accessor for that. 

Hopefully that answers your questions.
