### ISSUE TITLE
multi binder support

### ISSUE THREAD

**Issue by tajdars** [spring-cloud/spring-cloud-sleuth#1210]
With spring-cloud-sleuth-stream, I was able to use different RabbitMq binders for springClodBus, sleuth and application-specific .

Any ideas/examples on how to approach this without spring-cloud-sleuth-stream ?

(I want to send Zipkin Traces via  dedicated RabbitMq to  the centralized Zipkin Server).

**Comment by tajdars** [comment]
OK, i got this to work with by specifying the Zipkin  Collector RabbitMq separately using just spring.rabbitmq.host and other related properties.

Seems like this approach is prone to error.

spring-cloud-sleuth-stream looked much cleaner in terms of separating out the multiple streams w/o the risk of configs getting mixed up.

Thoughts ?

**Comment by marcingrzejszczak** [comment]
So you would like to have a separate set of propeties e.g. `spring.zipkin.rabbitmq.address` etc. that you would like to configure instead of using the main ones? 

@adriancole @shakuzen I find it a valid concern actually. We could add this for Hoxton as a new feature in such a way that if such properties are set, we'll take them into account. If not we'll default to the main rabbitmq ones. WDYT?

**Comment by tajdars** [comment]
Yup, separate namespacing for zipkin  rabbitmq/kafka will help with clarity.

**Comment by shakuzen** [comment]
> We could add this for Hoxton as a new feature in such a way that if such properties are set, we'll take them into account. If not we'll default to the main rabbitmq ones. WDYT?

Sounds reasonable to me. I don't know if there's anything else doing this type of thing already. We'd probably have to be careful to not make a bean of the connection thingy so there isn't more than one for auto-wiring. I assume that is fine since application code will want the one made by Boot in the "normal" namespace.

**Comment by adriancole** [comment]
would be best imho to match zipkin property names when not using normal spring

https://github.com/openzipkin/zipkin-reporter-java/blob/master/amqp-client/src/main/java/zipkin2/reporter/amqp/RabbitMQSender.java#L74

probably already the case just mentioning
