### ISSUE TITLE
Bug Report  -Scheduled- do not report error span 

### ISSUE THREAD

**Issue by wuyupengwoaini** [spring-cloud/spring-cloud-sleuth#1215]
https://github.com/spring-cloud/spring-cloud-sleuth/blob/ebcd73e4be1b7fa0d5e03292a3e695fb7c4db615/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/scheduling/TraceSchedulingAspect.java#L60-L75

when error occurs ,it do not report error span

**Comment by muzakhan** [comment]
<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-spring</artifactId>
		</dependency>

<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zipkin</artifactId>
		</dependency>

	<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>

and in properties file I have configured the properties as 
server.port=8081
spring.application.name=movie-catalog-info
management.endpoints.web.exposure.include=*
spring.zipkin.sender.type=activemq
spring.zipkin.activemq.addresses=tcp://localhost:61616
spring.zipkin.activemq.queue=zipkin

while launching I was getting error as below

Description:

Parameter 2 of method reporter in org.springframework.cloud.sleuth.zipkin2.ZipkinAutoConfiguration required a bean of type 'zipkin2.reporter.Sender' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'rabbitSender' in 'ZipkinRabbitSenderConfiguration' not loaded because @ConditionalOnBean did not find required type 'org.springframework.amqp.rabbit.connection.CachingConnectionFactory'
	- Bean method 'restTemplateSender' in 'ZipkinRestTemplateSenderConfiguration' not loaded because ZipkinSender org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration kafka sender type


Action:

Consider revisiting the entries above or defining a bean of type 'zipkin2.reporter.Sender' in your configuration.

**Comment by marcingrzejszczak** [comment]
Can you please format the code and provide any meaningful information like e.g. Used versions?

**Comment by muzakhan** [comment]
Spring Cloud Version: Hoxton.M2

For distributed tracing I have used Spring Cloud Sleuth and Activemq as Span Collector and Zipkin instead of sending  span via http to Zipkin server I am using activemq from there Zipkin poll the message.  For this I have used 3 dependency in our pom.xml

1. spring-cloud-starter-sleuth
2. spring-cloud-starter-zipkin
3. spring-boot-starter-activemq

and in applicatio.properties file 

server.port=8081
spring.application.name=movie-catalog-info
management.endpoints.web.exposure.include=*
spring.zipkin.sender.type=activemq
spring.zipkin.activemq.addresses=tcp://localhost:61616
spring.zipkin.activemq.queue=zipkin

While launching the application I am getting error as below

Description:

Parameter 2 of method reporter in org.springframework.cloud.sleuth.zipkin2.ZipkinAutoConfiguration required a bean of type 'zipkin2.reporter.Sender' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'rabbitSender' in 'ZipkinRabbitSenderConfiguration' not loaded because @ConditionalOnBean did not find required type 'org.springframework.amqp.rabbit.connection.CachingConnectionFactory'
	- Bean method 'restTemplateSender' in 'ZipkinRestTemplateSenderConfiguration' not loaded because ZipkinSender org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration kafka sender type


Action:

Consider revisiting the entries above or defining a bean of type 'zipkin2.reporter.Sender' in your configuration.
