### ISSUE TITLE
Add trace ID as header comment on database queries

### ISSUE THREAD

**Issue by Diagoras** [spring-cloud/spring-cloud-sleuth#1227]
Let me know if you think this issue should be opened against Brave instead, or if it's just too wacky for Sleuth to support at all.

We've found that when troubleshooting slow queries it can sometimes be difficult to definitively link a given query back to the operation that initiated it. This is especially true for DBAs that troubleshoot problems using a database-first perspective, where they hunt down slow queries using the database's profiling tools instead of application logs.

Do you think it makes sense to append the trace ID as a comment on transactions managed by Spring? That would allow database queries to be tied back to a trace ID, which in turn would link them back to the trace that produced them. For example:

```sql
-- X-B3-TraceId: b763b53c5c6ba343
BEGIN TRANSACTION;
SELECT * FROM foo WHERE baz = true;
COMMIT;
```

Please let me know what you think, and thanks for maintaining this library.

**Comment by shakuzen** [comment]
The idea is interesting and I see how it could be useful in some situations. Sleuth itself doesn't have any instrumentation of JDBC stuff. Brave offers some (mysql and p6spy), but I don't think any of them have the ability to change the query being executed (to add the comment). It looks like [datasource-proxy](http://ttddyy.github.io/datasource-proxy/docs/current/user-guide/) can via a `QueryTransformer`.

The implications of a unique comment in every query (or transaction) probably also needs to be considered for various databases.

> Do you think it makes sense to append the trace ID as a comment on transactions managed by Spring?

Targeting the transaction instead of individual queries is interesting. I'm not very familiar with customizing Spring's transaction support like this, so I'm not sure how would be best to achieve this.

Regardless, I think a feature like this would probably be best as disabled by default if it does get added.

**Comment by Diagoras** [comment]
> Targeting the transaction instead of individual queries is interesting.

Yeah, I went for it since it seems easier to do than targeting queries and because Spring already manages transactions. There's probably a good point to be made that queries are the more natural target, though, but I figure tracing them would be a lot more complex.

> Regardless, I think a feature like this would probably be best as disabled by default if it does get added.

Agreed.

**Comment by marcingrzejszczak** [comment]
I think that this should go to Brave and Sleuth would just autoconfigure the beans.

**Comment by Diagoras** [comment]
@marcingrzejszczak Makes sense to me. I'll close this ticket then, and open one against Brave instead. Thanks for taking a look and giving feedback.
