### ISSUE TITLE
support pattern for propagation_keys

### ISSUE THREAD

**Issue by davinkevin** [spring-cloud/spring-cloud-sleuth#1358]
Hi, 

I'm working on a set of microservice and our goal is to propagate multiple headers inside a service mesh to use them with Istio to do some canary release. 

Our only endpoint in our cluster in the UI app which has multiple endpoint. We would like, with spring cloud sleuth, be able to propagate headers inside the cluster which is simple to do thanks to https://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html#prefixed-fields by defining in my case 

```yaml
spring:
  sleuth:
    propagation-keys: x-company-app
```

Thanks to that, if someone sends an header `x-company-app: v2` we can move the traffic to `app: v2` pods. 

But, this solution doesn't scale well because we have to add every potential header to the UI application every time we add a microservices behind it (and inside every intermediate microservices). 

Could it be possible to propagate headers based upon a regex or just those starting by the prefix defined inside `spring.sleuth.propagation-keys` ? For me, it seems to be a standard behavior but I didn't find any issue or example in the documentation talking about it.

Thanks

**Comment by marcingrzejszczak** [comment]
Pinging the Brave folks cause I guess it should be added there first @devinsba @shakuzen @adriancole

**Comment by shakuzen** [comment]
See prior related work/ideas/discussion in https://github.com/apache/incubator-zipkin-brave/pull/577. The concern about information leakage is increased when propagating an unbounded regex of keys that can be sent to third-parties outside of your trusted system. Also, if the keys can be set by untrusted users (e.g., as HTTP headers in an initial HTTP request from a browser), that seems like a DOS attack vector due to the cost of propagation being proportional to the number of propagated keys.

Perhaps this is still something worth considering, but we should be careful to avoid making configuring vulnerable setups easy, especially if users won't understand such potential issues when configuring this.

**Comment by marcingrzejszczak** [comment]
I'm closing this issue here. Once Brave gets things updated we can reopen this one.
