### ISSUE TITLE
Default to rate-limited sampler instead of percentage

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1398]
Brave now supports a rate-limited sampling approach. In the next big version of spring cloud sleuth/boot, we should consider defaulting to a rate-limited approach. This will help sites from accidentally overwhelming while still allowing a "100%" experience for a while.

Picking the "traces per second" value can be tricky, but as this corresponds roughly to transactions per second, 1000 might make sense. Note: this is per instance so you can imagine if someone has 40 servers this would default to a max of 40K traces per second.

**Comment by shakuzen** [comment]
A default rate of 1000 sounds very high to me, especially compared to the previous default of 10% (would need at least 10k requests per second per edge instance to match). The idea of the default (if I'm not mistaken) is to provide something reasonably safe for production (if a user doesn't explicitly configure the sampler) and I think for a lot of users, 1000 traces per second per (edge) instance is effectively 100% tracing. I would suggest defaulting to 1-10 traces per second. This still provides a better getting started experience - a local demo or development environment probably won't exceed this and therefore no confusion about traces not showing in Zipkin. In production, it should not overwhelm a typical Zipkin deployment, and ultimately, users will want to adjust the sampler based on their testing.

**Comment by adriancole** [comment]
I agree with tommy, in hind sight 1000 is high.. I'm glad it started the
conversation.

The rational was someone wanted 100% sampling and could handle it and if we
change default to a low amount, they will silently not get all when they
wanted all. It could be the better punch to loudly warn about the default
change and that any settings you rely on should be actively configured.

aws defaults to 1/second
https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html
new relic defaults to 10/second
https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/get-started/how-new-relic-distributed-tracing-works#sampling

so yeah 10 is probably a good number especially to reduce questions as
people likely can't click refresh faster than 10x a second when testing

make sense?

**Comment by shakuzen** [comment]
> It could be the better punch to loudly warn about the default change and that any settings you rely on should be actively configured.

Yes, that is best practice for users and they really should be doing this for sampling, but we still need to be careful about the default because not all users will explicitly configure it.

Thanks for the references to other system's default sampling. This is good for comparison.
X-Ray's is a mix of rate-limited + probabilistic. I wonder what the motivation for this.
> By default, the X-Ray SDK records the first request each second, and five percent of any additional requests.

New Relic's default is 10 traces per **minute** rather than per second. Which would be about 0.167 per second.
> To adhere to these limits, the default number of traces at the trace origin is 10 traces per minute.

I would still lean closer to or just 1 trace per second as the default. I think for most local/demo/test things that will still trace everything while limiting overhead/network/storage costs until the operator understands their capacity and characteristics (e.g. average spans per trace, bytes per span).

**Comment by marcingrzejszczak** [comment]
So instead of https://github.com/spring-cloud/spring-cloud-sleuth/commit/69248fecc6f67d481f94da2bed7e689d1f624cd0 you'd do just 1 ?

**Comment by adriancole** [comment]
@abhiksingh do you recall the rationale for the tiered default in x-ray? we are looking for a safer default in sleuth though an overflow that's percentage based will still have a problem on surge.

**Comment by abhiksingh** [comment]
After a bunch of analysis in 2016, we found that ~80% of web/business apps do 1 req/s or less so the reservoir of 1 req/s seemed reasonable. For the overflow we chose 5% to make it so that by default tracing was some percentage of a request cost (especially for Lambda). Don’t recall the exact percentage we were going for. The rationale for choosing both reservoir and probabilistic sampling was to ensure there was a constant flow of requests to do service maps, and other analysis that customers use X-Ray for.

**Comment by adriancole** [comment]
Thanks, Abhishek.

One follow-up about this.. could you not also get a constant flow with an
upper bound? ex 1/s, max(5%, 100/s)
This could seemingly cause less throttled errors in AWS, or overloads on
our side (even low traffic sites, people can still make traces in a for
loop)

maybe in practice it isn't needed as few do that... I can see why 5% could
be a pragmatic default ignoring the surge problem.

**Comment by abhiksingh** [comment]
Yeah the max works if you want to limit to 100 req/s. In our case we have customers sending multiple orders of magnitude larger so using max of (5%, 100r/s) wouldn’t work for those customers. Also the reason why we made sampling controllable from the service APIs so customers can set it dynamically and on the fly.

**Comment by adriancole** [comment]
makes sense. thx abhishek

**Comment by adriancole** [comment]
@abhiksingh one last thing :)

I thought reality would be `((1/s, 5%), aggregate throttle)`, but I don't actually see any api-limit on segments per s. Is there none? https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html

This is closer to the concern about rate. basically a common setup and how much they can take per unit. Still, probably `(1/s, 5s)` could be a smart number except that most zipkin installs I know of do not do api throttling such as probably AWS does even if I can't find the limit..

**Comment by abhiksingh** [comment]
We do throttle on segments/s and overall size/frequency of segments received to ensure folks don’t use X-Ray as a data store for random use cases because for their use case it ends up cheaper than other storage. We’ve had a few try to use it as a ledger. 

These limits are dynamically calculated hence the challenge documenting them. Customers can reach out via support to change/adjust them based on their use case.

Recalling off the top of my head - don’t quote me on this :) - I think the segments/s is by default ~500/s and we try to limit overall trace size to ~500KB

**Comment by adriancole** [comment]
> don’t quote me on this :)

hehe smart man
