### ISSUE TITLE
ZipkinBackwardsCompatibilityAutoConfiguration is not overriding the `zipkinReporter` bean name

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-sleuth#1400]
See https://github.com/spring-cloud/spring-cloud-gcp/issues/1705

`ZipkinBackwardsCompatibilityAutoConfiguration` should produce the reporter bean name specified in [REPORTER_BEAN_NAME](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/ZipkinAutoConfiguration.java#L77)

/cc @marcingrzejszczak @TYsewyn

**Comment by TYsewyn** [comment]
AFAIC it shouldn't do that since `ZipkinBackwardsCompatibilityAutoConfiguration` kicks in before `ZipkinAutoConfiguration `, and it's `ZipkinAutoConfiguration` which is going to create the sender with the REPORTER_BEAN_NAME if it doesn't exist.
If you disable zipkin - or sleuth altogether for that matter - it won't load both auto configuration classes.

**Comment by marcingrzejszczak** [comment]
@TYsewyn can you link the issue from GCP here that proves that things work fine (or not)?

**Comment by TYsewyn** [comment]
Sure, it's this PR: https://github.com/spring-cloud/spring-cloud-gcp/pull/1740

**Comment by saturnism** [comment]
but user shouldn't need to disable zipkin manually, since the original backward compatible behavior should be overriding the reporter so that there is only one.

**Comment by TYsewyn** [comment]
Ok, totally makes sense :)

So there are 2 possible solutions to this then AFAIC:
- Rename the `stackdriverSender` bean to REPORTER_BEAN_NAME
- Backport what is on master

Implementing it in a way like we did for [the configuration](https://github.com/spring-cloud/spring-cloud-gcp/blob/1.1.x/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L102) of the trace id length would not be possible because you can't turn it on then, even if you explicitly said so in your properties file.

**Comment by saturnism** [comment]
thank you!

**Comment by TYsewyn** [comment]
Closed since a fix has been provided for spring-cloud-gcp (spring-cloud/spring-cloud-gcp#1744)
