### ISSUE TITLE
SpanId not copied to ParentSpanId (Istio service mesh + Feign calls)

### ISSUE THREAD

**Issue by riccalioliojr** [spring-cloud/spring-cloud-sleuth#1404]
Context:
* Kubernetes cluster
* Istio service mesh
* Java microservices all using:
    * Spring Cloud Feign 1.4.4.RELEASE
    * Spring Boot 1.5.12.RELEASE
    * Sleuth 1.3.5.RELEASE

The trace IDs are correctly being propagated in subsequent Feign calls but for some reason, the parent span ID is always new and is not copied from the caller's span ID.

To use Sleuth, I just added the POM dependency and no other special configuration were done.

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
			<version>${sleuth.version}</version>
		</dependency>
```

**Comment by marcingrzejszczak** [comment]
Can you please check if it works fine with a more recent version of Sleuth? The one you're using will soon be outdated and we have fixed a lot of issues in the newer versions

**Comment by riccalioliojr** [comment]
@marcingrzejszczak I was able to upgrade it until 1.3.6.RELEASE but it has the same issue. I am encountering errors when use 2.0.0 or higher probably because of my Spring Boot version. Is this an expected version incompatibility? Or is there a Sleuth version higher than 1.3.6 that should work with Spring Boot 1.5.12?

**Comment by marcingrzejszczak** [comment]
Please read about the compatibility matrix of Boot vs Cloud versions over here https://spring.io/projects/spring-cloud.

```

Release Train | Boot Version
-- | --
Greenwich | 2.1.x
Finchley | 2.0.x
Edgware | 1.5.x
Dalston | 1.5.x
```

If you need to check out Spring Cloud Sleuth versions you can for example visit the project website https://spring.io/projects/spring-cloud-sleuth#learn

You could go to maven central and search for a given artifact and check out its version.

Last but not least since you're in the Sleuth project you could just check out the releases https://github.com/spring-cloud/spring-cloud-sleuth/releases

**Comment by riccalioliojr** [comment]
@marcingrzejszczak Looks like we need to start much sooner our planned upgrade to Spring Boot 2. Thank you for your time!
