### ISSUE TITLE
Investigate issue with deferring results

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#141]
In a slim down version of a project using Sleuth with DeferredResult and RxJava, I'm still seeing the issue where a span is living longer than the request. Every other request has a warning about the previous request's span still being open. I tried closing the span in the Observable.onComplete and DeferredResult onCompletion callback. Is there a way to ensure the span is closed or a another way that is recommended to have a RxJava async controller with Sleuth.? The sample project code is at: https://github.com/mikesarver/stuff-svc thanks for any help.

**Comment by dsyer** [comment]
There's a bug in `DefaultTracer` (probably) because the parent span is not the current span when the background work starts, but it is set into the thread context in `joinTrace()` and then not cleared by the `close()`.

It would also be nice to support RxJava background threads out of the box, but that's a new feature.

**Comment by shivangshah** [comment]
@dsyer any ideas on when Rxjava background threads will be supported? I was looking at the example here: http://blog.mabn.pl/2014/11/rxjava-logback-and-mdc-threadlocal.html. Just wasn't sure how we can setup to copy tracer. Help Appreciated!

**Comment by dsyer** [comment]
This is an old issue. Please open a new one if you have a new feature request.

**Comment by shivangshah** [comment]
Will do.
