### ISSUE TITLE
Including sleuth with resilence4j circuit breaker causes package protected getter to return null

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-sleuth#1630]
https://gist.github.com/snicoll/cd93c6e089aadd55089f58df8086a1d5

> git clone https://github.com/snicoll/spring-petclinic-microservices.git
cd spring-petclinic-microservices
git checkout wavefront
./mvnw clean install
IMPORTANT: do not use the docker stuff as it’s going to create an account for each service since it doesn’t read the token from your home directory. My docker-fu is too low to fix that
You need to run spring-petclinic-config-server first. Then run spring-petclinic-discovery-server. Once those two are up and running you can run the other ones.

Then change to Hoxton.SR4 and run gateway

**Comment by marcingrzejszczak** [comment]
So this is fixed via https://github.com/spring-cloud/spring-cloud-circuitbreaker/commit/285e6fa473ac20636ebb038ea47733e3cec58457 ?

**Comment by ryanjbaxter** [comment]
I believe so

**Comment by snicoll** [comment]
That commit rather eliminates the issue from happening as far as I can see. The original cause is still there for any other candidate that would have a package protected method.

**Comment by spencergibb** [comment]
yes, there is still a problem

**Comment by marcingrzejszczak** [comment]
Is this still an issue? I've managed to run the API gateway only with `connection refused` exception for Hoxton.SR7 and latest Boot.

**Comment by snicoll** [comment]
@marcingrzejszczak I think so as we've indicated right above your comment. Resilience4j has nothing to do with the problem, it just happens to exhibit the problem when beans are proxied. To reproduce, you could remove the fix made in Resilience4j and try again.

**Comment by marcingrzejszczak** [comment]
Cool, closing the issue then

**Comment by jonatan-ivanov** [comment]
I looked into this and it seems the cause is the Sleuth AOP Proxy (`TraceCircuitBreakerFactoryAspect`).
If I turn it off (`spring.sleuth.circuitbreaker.enabled: false`), the issue is gone, if I interfere with the cglib proxying mechanism and don't let the bean to be proxied by the tracing aspect, the issue is gone.  If I call the same method on the proxied object from the debugger (eval expr), I get back the instance (from code it returns null).

I'm going to continue this and take a look at this later but I think the issue is around the `TraceCircuitBreakerFactoryAspect`. Maybe the `Pointcut` or the Config order is wrong. I haven't seen any obvious issues so far but the `Advice` is definitely not executed from the debugger so I guess the proxy is basically an empty object with null fields.

**Comment by jonatan-ivanov** [comment]
I have some updates: it seems the issue is related to the fact that `spring-boot-devtools` restarts the app using a `RestartClassLoader`. If I prevent the restart in any ways (e.g.: removing devtools), the issue disappears. I don't think the restart itself is the root cause, I think it is related to the classloader so you can skip to the next section but for the sake of documenting this, I put here a couple of ways to do this (also if you want to play with it):

- [remove the `spring-boot-devtools` dependency from the project](https://github.com/snicoll/spring-petclinic-microservices/blob/73cbebcd9f41e939bdcab4e3a386cc232400564d/spring-petclinic-api-gateway/pom.xml#L31-L35)
- [remove `org.springframework.boot.devtools.restart.RestartApplicationListener` from `spring.factories` in devtools](https://github.com/spring-projects/spring-boot/blob/v2.3.6.RELEASE/spring-boot-project/spring-boot-devtools/src/main/resources/META-INF/spring.factories#L7)
- start the app with `-Dspring.devtools.restart.enabled=false`
- [set `restartOnInitialize` to false in `RestartApplicationListener::onApplicationStartingEvent` with the debugger](https://github.com/spring-projects/spring-boot/blob/v2.3.6.RELEASE/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/RestartApplicationListener.java#L70)
- [comment out the `mainMethod.invoke` in `RestartLauncher::run`](https://github.com/spring-projects/spring-boot/blob/v2.3.6.RELEASE/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/RestartLauncher.java#L49)
also comment out `SilentExitExceptionHandler.exitCurrentThread();` in `Restarter::immediateRestart`

It seems, the root cause is in connection with the fact that the restart is executed using a `RestartClassLoader` that wraps the original classloader, see: [Restarter::doStart](https://github.com/spring-projects/spring-boot/blob/v2.3.6.RELEASE/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/Restarter.java#L279). If I change back the classloader to the original one instead of the wrapped one, the issue disappears, e.g.: [`return relaunch(this.applicationClassLoader);`](https://github.com/spring-projects/spring-boot/blob/v2.3.6.RELEASE/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/Restarter.java#L283).  
Though, I don't think that this is the fault of the `RestartClassLoader` itself, if I wrap the original classloader into a slightly different one, the issue still persists, e.g.: `new URLClassLoader(urls, this.applicationClassLoader)`.

I believe, the root cause lies somewhere around the AOP proxying mechanism. If I let the restart happen with the `RestartClassLoader`, it is still possible to eliminate the issue by updating the `ClassLoader` or the `ClassLoaderData`  in the gateway app; basically anywhere from [`CglibAopProxy::getProxy`](https://github.com/spring-projects/spring-framework/blob/v5.2.11.RELEASE/spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java#L159) through [`ObjenesisCglibAopProxy::createProxyClassAndInstance`](https://github.com/spring-projects/spring-framework/blob/v5.2.11.RELEASE/spring-aop/src/main/java/org/springframework/aop/framework/ObjenesisCglibAopProxy.java#L56) till [`AbstractClassGenerator:: create`](https://github.com/spring-projects/spring-framework/blob/v5.2.11.RELEASE/spring-core/src/main/java/org/springframework/cglib/core/AbstractClassGenerator.java#L305) (super class of [`Enhancer`](https://github.com/spring-projects/spring-framework/blob/v5.2.11.RELEASE/spring-core/src/main/java/org/springframework/cglib/proxy/Enhancer.java#L93))

The `ClassLoaderData` is different in the case when the `RestartClassLoader` is used  
([`ClassLoaderData data = cache.get(loader);`](https://github.com/spring-projects/spring-framework/blob/v5.2.11.RELEASE/spring-core/src/main/java/org/springframework/cglib/core/AbstractClassGenerator.java#L305))  
vs. the case when the `ClassLoaderData` is acquired using the the original classloader
(`ClassLoaderData data = cache.get(loader.parent);`).  
Also the issue disappears in the second case.

Based on this, I don't think that the issue is caused by Sleuth. If you have any idea about what could go wrong, please let me know.

**Comment by jonatan-ivanov** [comment]
Closing this in favor of https://github.com/spring-projects/spring-boot/issues/25367
