### ISSUE TITLE
TraceWebFilter not set a real remote client IP when behind a web proxy

### ISSUE THREAD

**Issue by fanticat** [spring-cloud/spring-cloud-sleuth#1683]
**Describe the bug**
When a service which behind a web proxy, such as nginx/appach, the code in `TraceWebFilter.java` can not identify this，it override the `barve.http.HttpServerRequst` and pickup `delegate.getRemoteAddress();`, then this returns a proxy's ip.  `barve.http.HttpServerRequst` handled this case actually，is there any possible to call `super.parseClientIpAndPort()` before this?

[Code](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java)

```java
               @Override
		public boolean parseClientIpAndPort(Span span) {
			InetSocketAddress addr = delegate.getRemoteAddress();
			if (addr == null) {
				return false;
			}
			return span.remoteIpAndPort(addr.getAddress().getHostAddress(),
					addr.getPort());
		}
```

**Comment by marcingrzejszczak** [comment]
Sure, are you willing to create a test and change code in the 2.2.x branch? (I'll then merge 2.2.x to master).

**Comment by dennysfredericci** [comment]
Hello from Belgium! :blush:

@fanticat Are you using an embedded servlet container? Is your web proxy passing the **X-Forwarded-For** header? 

If your answer is yes for both questions you can add a spring boot configuration to get the right remote address!  :rocket:

For Spring Boot 2.1 or previous versions add the configuration below:

`server.use-forward-headers = true`

Since Spring Boot 2.2 this property was deprecated, but we have the same behavior using the configuration below:

`server.forward-headers-strategy = framework`

@marcingrzejszczak  said that, Is this a valid enhancement/change:question:

**Comment by marcingrzejszczak** [comment]
Hey @dennysfredericci your suggestion is a good workaround, however I think that this actually is a bug on the Sleuth side. Since we're breaking the way things work from Brave's perspective.
