### ISSUE TITLE
Spring Boot application does not start with spring-cloud-sleuth and spring-boot-starter-websocket

### ISSUE THREAD

**Issue by morrijr** [spring-cloud/spring-cloud-sleuth#1797]
**Describe the bug**
Generated project from [start.spring.io](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.4.0.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=cloud-starter-sleuth,websocket) with cloud-starter-sleuth and websocket (spring-boot-starter-websocket)

Compile and run fails with

```
Field setter in org.springframework.cloud.sleuth.autoconfig.instrument.messaging.TraceWebSocketAutoConfiguration required a single bean, but 2 were found:
	- traceMessagePropagationSetter: defined by method 'traceMessagePropagationSetter' in class path resource [org/springframework/cloud/sleuth/autoconfig/instrument/messaging/TraceSpringMessagingAutoConfiguration.class]
	- traceMessagePropagationGetter: defined by method 'traceMessagePropagationGetter' in class path resource [org/springframework/cloud/sleuth/autoconfig/instrument/messaging/TraceSpringMessagingAutoConfiguration.class]
```

Swapping line 19 in the pom.xml from
<spring-cloud.version>2020.0.0-M6</spring-cloud.version>
to
<spring-cloud.version>2020.0.0-M5</spring-cloud.version>
allows the application to start.

[demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/5666722/demo.zip)

**Comment by jonatan-ivanov** [comment]
@morrijr Thank you very much for the repro steps and the example I was able to repro and fix this locally, here's what happens:

It seems M6 introduced two dependencies in [`TraceWebSocketAutoConfiguration`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/v3.0.0-M6/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/messaging/TraceWebSocketAutoConfiguration.java#L58-L62):
- `Propagator.Setter<MessageHeaderAccessor>`
- `Propagator.Getter<MessageHeaderAccessor>`

Both of them are created in [`TraceSpringMessagingAutoConfiguration`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/v3.0.0-M6/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/messaging/TraceSpringMessagingAutoConfiguration.java#L35-L45). If you look closer, they are referencing the very same object: `MessageHeaderPropagation.INSTANCE`
This is possible because [`MessageHeaderPropagation`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/v3.0.0-M6/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessageHeaderPropagation.java#L43-L44) implements both `Propagator.Setter<MessageHeaderAccessor>` and `Propagator.Getter<MessageHeaderAccessor>`. So when the context is created there will be two beans:
- `traceMessagePropagationSetter`
- `traceMessagePropagationGetter`

Both of them are `Propagator.Setter<MessageHeaderAccessor>` **and** `Propagator.Getter<MessageHeaderAccessor>` at the same time. So we have two beans both of them are getters and setters so we have two getters and two setters at runtime and Spring does not know which one is the right one.

 One possible fix is autowiring these beans using their id instead of by type or splitting the implementation (this can be trickier if the ge and set logic depends on common code base).

**Comment by marcingrzejszczak** [comment]
I've decided to go with splitting the enum into two classes. That enum was bizarre in the first place
