### ISSUE TITLE
Trace a REST --> multiple SOAP requests with Zipkin

### ISSUE THREAD

**Issue by RALGIE** [spring-cloud/spring-cloud-sleuth#1801]
I'm trying to trace a REST request that triggers multiple SOAP request with Zipkin. All requests are shown in the Zipkin interface but the relation between the rest and the multiple SOAP request aren't displayed. What should I add or configure to get this working?

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by RALGIE** [comment]
I'm trying to trace a REST request that triggers multiple SOAP request. All requests are shown in the Zipkin interface but the relation between the rest and the multiple SOAP request aren't displayed. What should I add or configure to get this working?
spring-cloud.version Edgware.RELEASE

Sample can I make but takes some time. We have a customer that is having issues and is time sensitive.

**Comment by marcingrzejszczak** [comment]
Edgware is not supported. Please upgrade
