### ISSUE TITLE
Cloud Gateway: no trace at all with Boot 2.4.1 + 3.0.0-SNAPSHOT / M6

### ISSUE THREAD

**Issue by zokkr** [spring-cloud/spring-cloud-sleuth#1806]
**Describe the bug**
When trying to add tracing to Spring Cloud Gateway, no log entries contain a trace id, even though the log is in a format one would expect when adding Sleuth.

![Screenshot_20201212_172105](https://user-images.githubusercontent.com/30506406/101989477-d4597b00-3ca0-11eb-82b7-d69dce719d12.png)

This only happens in the versions Boot 2.4.1 + Cloud 2020.0.0-SNAPSHOT (also tested with M6) - when downgrading to 2.3.4.RELEASE + Hoxton.SR9, the tracing works as intended:

![Screenshot_20201212_172033](https://user-images.githubusercontent.com/30506406/101989480-dc191f80-3ca0-11eb-92eb-519b637b3149.png)

**Sample**
Sample with two branches:
[not working: 2.4.1 + 2020.0.0-SNAPSHOT](https://github.com/zokkr/spring-cloud-gateway-sleuth-notraceid)
[working: 2.3.4.RELEASE + Hoxton.SR9](https://github.com/zokkr/spring-cloud-gateway-sleuth-notraceid/tree/2.3.4_Hoxton.SR9)

Start app and perform a GET to http://localhost:9080/

**Comment by marcingrzejszczak** [comment]
Gateway tracing does work. What you're doing is you're creating a controller within a gateway application and expect that controller to be automatically traced, which will not work.

With 2020.0.0 we've changed the default Gateway reactor instrumentation mode to `manual`. That means that we're taking care of proper passing of tracing context when actual Gateway internals are used. Since you're using a WebFlux controller - that's beyond the scope of our automated instrumentation. What you would need to do is to manually wrap a given operation to be in scope as presented below

```java
@SpringBootApplication
@RestController
@Slf4j
public class TestingGatewaySleuthApplication {

  public static void main(String[] args) {
    SpringApplication.run(TestingGatewaySleuthApplication.class, args);
  }

  @Autowired
  Tracer tracer;

  @Autowired
  CurrentTraceContext currentTraceContext;

  @GetMapping
  public void logTest(ServerWebExchange exchange) {
    WebFluxSleuthOperators.withSpanInScope(tracer, currentTraceContext, exchange, () -> log.error("TESTABCTEST"));
  }
}

```

Then you get the following log entry:

```
2020-12-14 09:33:23.323 ERROR [,f79cf9596397093f,f79cf9596397093f] 35314 --- [or-http-epoll-2] s.s.t.TestingGatewaySleuthApplication    : TESTABCTEST
```

You can read more about this in the documentation https://docs.spring.io/spring-cloud-sleuth/docs/3.0.0-SNAPSHOT/reference/html/integrations.html#sleuth-reactor-integration and here https://docs.spring.io/spring-cloud-sleuth/docs/3.0.0-SNAPSHOT/reference/html/integrations.html#sleuth-http-server-webflux-integration

**Comment by zokkr** [comment]
Hi @marcingrzejszczak 

thanks for your answer, I wasn't aware of that in particular.
However, I built this sample originally because also the Cloud Gateway standard logs are not filled at all with tracing information for me. Its not included eg. in the RoutePredicateHandlerMapping of the Gateway. It is in fact correct, that the headers are sent to the downstream apps, but how can I enable having those information in the log of the Gateway, too - without changing the instrumentation type? Or is that the way to go?

Below is a full log of a request that is routed by the gateway, and as you can see, only the app name is present in the log:
![Screenshot_20201224_141459](https://user-images.githubusercontent.com/30506406/103090792-6d1dbe00-45f2-11eb-8cbe-4448ce641209.png)

While the same request with an ON_LAST instrumentation type looks like this (ON_EACH being almost the same):
![Screenshot_20201224_141334](https://user-images.githubusercontent.com/30506406/103090753-43fd2d80-45f2-11eb-8254-9b04451404ff.png)
