### ISSUE TITLE
Feign instrumentation generates invalid traceparent when using W3C propagation type

### ISSUE THREAD

**Issue by sanyarnd** [spring-cloud/spring-cloud-sleuth#1809]
Using `2020.0.0-RC1` and `Spring Boot 2.4.1`.

1. Set `spring.sleuth.propagation.type=W3C,B3`
2. Register feign client
3. Feign send a request with broken headers (or at least headers cannot be processed by another Spring Application).

Generated headers:
```
POST http://127.0.0.1:8050/some-call HTTP/1.1
X-B3-TraceId: caf0bc2f7b1e4ca1
X-B3-SpanId: 5e2dfa62adeb7454
X-B3-ParentSpanId: caf0bc2f7b1e4ca1
X-B3-Sampled: 0
traceparent: 00-caf0bc2f7b1e4ca1                -5e2dfa62adeb7454-00

Binary data
```
The empty space in `traceparent` is actually `NULL` bytes:
```
0 = 48
1 = 48
2 = 45
3 = 99
4 = 97
5 = 102
6 = 48
7 = 98
8 = 99
9 = 50
10 = 102
11 = 55
12 = 98
13 = 49
14 = 101
15 = 52
16 = 99
17 = 97
18 = 49
19 = 0
20 = 0
21 = 0
22 = 0
23 = 0
24 = 0
25 = 0
26 = 0
27 = 0
28 = 0
29 = 0
30 = 0
31 = 0
32 = 0
33 = 0
34 = 0
35 = 45
36 = 53
37 = 101
38 = 50
39 = 100
40 = 102
41 = 97
42 = 54
43 = 50
44 = 97
45 = 100
46 = 101
47 = 98
48 = 55
49 = 52
50 = 53
51 = 52
52 = 45
53 = 48
54 = 48
```

**Comment by marcingrzejszczak** [comment]
Any chance for a small sample to reproduce this?

**Comment by sanyarnd** [comment]
```kotlin
package bug

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.cloud.openfeign.EnableFeignClients
import org.springframework.cloud.openfeign.FeignClient
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

@EnableFeignClients
@SpringBootApplication
class Application

fun main(args: Array<String>) {
    SpringApplication(Application::class.java).run(*args)
}

@RestController
@RequestMapping("/w3c-bug")
class Controller(
    val headerClient: HeaderClient
) {
    @PostMapping
    fun headers(): String = "Works"

    @GetMapping
    fun remoteCall(): String = headerClient.bug()
}

@FeignClient(value = "headerClient", url = "localhost:8080")
interface HeaderClient {
    @PostMapping("/w3c-bug")
    fun bug(): String
}
```
and
```properties
spring.sleuth.propagation.type=W3C
spring.zipkin.enabled=false

logging.level.root=DEBUG
```

full project:
[feign-sleuth-w3c.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/5704133/feign-sleuth-w3c.zip)

**Comment by jonatan-ivanov** [comment]
@sanyarnd Thank you for reporting this and for the sample project, I was able to reproduce the issue and find the root cause:

[`W3CPropagation`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/bridge/W3CPropagation.java#L135-L158) creates the [traceparent](https://www.w3.org/TR/trace-context/#traceparent-header).

In our case the traceId needs to consist of [exactly 32 digits](https://www.w3.org/TR/trace-context/#version-format) but in sleuth the traceId is only 16 digits and the init values in the character array are zero bytes, the rest of the traceId is zeroed out (16 zeros).

The fix could be simple: adding leading zeroes to the traceId so that its length will be 32.

**Comment by marcingrzejszczak** [comment]
Hey @sanyarnd , can you check the latest snapshots to see if things are working fine?
