### ISSUE TITLE
Instrumentation of Spring Cloud Stream Kafka Streams

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-sleuth#1832]
Spring Boot 2.4.2 - Spring Cloud 2020.0.0

I'm processing messages in an application with Spring Cloud Stream Kafka Streams binder:

```
@Bean
fun processDeploymentFinished() = Function<KStream<MyKey, MyValue>, KStream<MyKey, ProcValue?>> { myValue ->
```

The received message does contain the `b3` header that should be used by Sleuth. The problem here is that Sleuth's instrumentation doesn't seem to be kicking in, as logs don't show the trace/span values:

```
2021-01-24 14:11:44.650  INFO [myapp,,] 7937 --- [-StreamThread-1]
```

**Comment by jonatan-ivanov** [comment]
As far as I remember, if you use spring-cloud-stream in an async way, tracing information is not propagated, see: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1822 but it should work if you use it in a synchronous way, i.e. using `StreamBridge` or `MessageChannel`. Though, I can be mistaken and this might be another use case.

Because of the missing propagation, the  received message should not contain any tracing information so the issue is indeed weird. Could you please create a minimal sample project that reproduces the issue?

Also, could you please check if tracing for Kafka is enabled?
```
spring.sleuth.messaging.kafka.enabled=true
spring.sleuth.messaging.messaging.kafka.enabled=true
spring.sleuth.integration.enabled=true
```

**Comment by codependent** [comment]
@jonatan-ivanov I've upload a sample project here: https://github.com/codependent/sleuth-kafka-streams/tree/main

The Rest controller uses a Kafka Producer to send a message propagating the correlation headers:

Controller: 

```
    @GetMapping("/sendMessage")
    fun send(@RequestParam text: String): Mono<Void> {
        logger.info("send() {}", text)
        return kafkaProducer.send(text)
    }
```

Producer:

```
    fun send(text: String): Mono<Void> {
        val dateTime = OffsetDateTime.now().toInstant().toEpochMilli()

        val message = MessageBuilder.withPayload(text)
            .setHeader(KafkaHeaders.MESSAGE_KEY, text)
            .setHeader(KafkaHeaders.TIMESTAMP, dateTime)
            .build()

        textSink.emitNext(message, Sinks.EmitFailureHandler.FAIL_FAST)
        return Mono.empty()
    }
```

Notice the `KafkaProducerConfiguration` where `MessagingSleuthOperators` is used to propagate the headers

```
@Configuration
class KafkaProducerConfiguration(private val beanFactory: BeanFactory) {

    private val logger = LoggerFactory.getLogger(javaClass)

    @Bean
    fun textSink(): Sinks.Many<Message<String>> = Sinks.many().unicast().onBackpressureBuffer()

    @Bean
    fun text(): Supplier<Flux<Message<String>>> = Supplier {
        textSink().asFlux().map {
            val msg = MessagingSleuthOperators.handleOutputMessage(beanFactory, MessagingSleuthOperators.forInputMessage(beanFactory, it))
            logger.debug("Produced message {}", msg)
            msg
        }
    }

}
```

Finally the KStream uses a Processor to access the message header:

```
@Configuration
class TextKStreamConfiguration {

    @Bean
    fun process() = Consumer<KStream<String, String>> { textStream ->
        textStream.process({

            object : Processor<String, String> {

                private val logger = LoggerFactory.getLogger(javaClass)
                private lateinit var context: ProcessorContext

                override fun init(context: ProcessorContext) {
                    this.context = context
                }

                override fun process(key: String, value: String) {
                    logger.info("Headers(b3) => {}", String(context.headers().lastHeader("b3").value()))
                    logger.info("Key {} - Value {}", key, value)
                }

                override fun close() {}
            }
        })
    }

}
```

Running `curl "localhost:8080/sendMessage?text=hello"`, you'll find the following logs, with a traceid/spanid (`[sleuth-kafka-streams,8fe5db1286923572,8fe5db1286923572] `) in the Rest controller. The b3 header is correctly sent in the Kafka message, and is available in the processor. However it isn't automatically intrumented, as you can see in the KStream logs (`[sleuth-kafka-streams,,]`):

```
2021-01-26 10:11:48.500  INFO [sleuth-kafka-streams,8fe5db1286923572,8fe5db1286923572] 57206 --- [ctor-http-nio-3] c.c.k.kafkasleuth.web.MessageController  : send() hello
2021-01-26 10:11:48.513  INFO [sleuth-kafka-streams,,] 57206 --- [-StreamThread-1] s.TextKStreamConfiguration$process$1$1$1 : Headers(b3) => 8fe5db1286923572-616e6b1720ccc089-0
2021-01-26 10:11:48.513  INFO [sleuth-kafka-streams,,] 57206 --- [-StreamThread-1] s.TextKStreamConfiguration$process$1$1$1 : Key hello - Value hello
```

**Comment by jonatan-ivanov** [comment]
Next time could you please provide a pure java example to rule out language-related issues?
Based on the example it seems you are trying to simulate the instrumentation done by sleuth and spring-cloud-stream manually. Since on the consumer side you are not doing the instrumentation, and I don't think this use-case is supported, tracing information is not propagated.

You can fix this in two ways:
- you do the instrumentation yourself
- you can use a supported way of consuming messages, e.g.: through `@KafkaListener`

Please reopen the issue if these does not work (with a pure-java example) or create a new one if you think this use-case should be supported.
