### ISSUE TITLE
Fail the context to start if both Brave and OTel is on the classpath

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-cloud/spring-cloud-sleuth#1855]
Sleuth supports both Brave and OTel but users need to decide which one do they want to use.
By default, the tracing library is Brave but if users want to use OTel, they need to exclude Brave. This feature should detect this scenario and let the users know about it.

**Comment by marcingrzejszczak** [comment]
If you have picked automatic tracer library picking mode then `OtelAutoConfiguration` is executed BEFORE `BraveAutoConfiguration`. That way `Tracer` bean is registered by OTel. Then conditionals on `BraveAutoConfiguration` are NOT matched

```java
// TRACE IS NOT MISSING
@ConditionalOnMissingBean({Tracer.class})
// ...
public class BraveAutoConfiguration {
```

I'll transfer this issue to Spring Cloud Sleuth OTel so that we explicitly break the context there.

**Comment by marcingrzejszczak** [comment]
Moved the issue to OTel https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/issues/36
