### ISSUE TITLE
Unresolved: Incorrect status code when using WebFlux with functional endpoints

### ISSUE THREAD

**Issue by flavium31** [spring-cloud/spring-cloud-sleuth#1896]
This issue is related to: #1851 and #1888 

**Describe the bug**
When using WebFlux with functional endpoint and `WebExceptionHandler` for intercepting exceptions and setting the status code on the response, the status code on the span is defaulted to 500 and does not reflect the final status code received by the client.

**Sample**
A small sample that reproduces it: https://github.com/flavium31/sleuth-otel-status-code-issue/tree/status-code-runtime-exception-functional

When the endpoint is called, the caller receives a 418 status code, however the printed span has a status code of 500:

```
'GET' : 63a8f0ab1a2f9a766aeae6000b8e7d3d 283259d20bb7eccb SERVER [tracer: org.springframework.cloud.sleuth:0.17.0] AttributesMap{data={net.peer.ip=localhost, net.peer.port=8080, http.method=GET, http.user_agent=PostmanRuntime/7.26.10, http.url=http://localhost:8080/test-functional, http.path=/test-functional, http.flavor=http, http.client_ip=localhost, mvc.controller.class=Application$$Lambda$450/0x0000000800437440, **http.status_code=500**}, capacity=128, totalAddedValues=10}
```

**Comment by marcingrzejszczak** [comment]
@rstoyanchev it seems that this https://github.com/spring-cloud/spring-cloud-sleuth/commit/5ab1c13f0cacd7d46b8528427c825f16fbfac216 doesn't work :grimacing:

**Comment by rstoyanchev** [comment]
Sleuth is implemented as a `WebFilter` which sits between a `WebExceptionHandler` and the actual handler like a functional endpoint. Unless the exception is in the `ResponseStatusException` hierachy it has no way of knowing what status will be chosen later in a ``WebExceptionHandler`. 

Generally speaking a `WebExceptionHandler` is more of a stopgap measure for exceptions that remain not handled otherwise. It is preferable to handle them closer to the handler, for example via `RouterFunctions#onError` for a functional endpoint, or at least translate to a `ResponseStatusException` somewhere through the `onResume` operator for example.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
