### ISSUE TITLE
Missing method error when trying to use otel

### ISSUE THREAD

**Issue by jimshowalter** [spring-cloud/spring-cloud-sleuth#1908]
`
springDependencyManagementVerson=1.0.11.RELEASE
sleuthVersion=3.0.2
sleuthOtelVersion=1.0.0-M7
springCloudReleaseTrainVersion=2020.0.2

plugins {
    id "io.spring.dependency-management" version "${springDependencyManagementVerson}"
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudReleaseTrainVersion}"
        mavenBom "org.springframework.cloud:spring-cloud-sleuth-otel-dependencies:${sleuthOtelVersion}"
    }
}

dependencies {
...
    implementation("org.springframework.cloud:spring-cloud-sleuth-zipkin:${sleuthVersion}")
    implementation("org.springframework.cloud:spring-cloud-starter-sleuth:${sleuthVersion}") {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-sleuth-brave'
    }
    //implementation("org.springframework.cloud:spring-cloud-sleuth-autoconfigure:${sleuthVersion}")
    implementation("org.springframework.cloud:spring-cloud-sleuth-otel-autoconfigure:${sleuthOtelVersion}")`

Launch service:

`
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

org.springframework.cloud.sleuth.autoconfig.zipkin2.ZipkinRestTemplateSenderConfiguration.restTemplateSender(ZipkinRestTemplateSenderConfiguration.java:57)

The following method did not exist:

    'java.lang.String org.springframework.cloud.sleuth.zipkin2.ZipkinProperties.getApiPath()'

The method's class, org.springframework.cloud.sleuth.zipkin2.ZipkinProperties, is available from the following locations:

    jar:file:/.../code/services/myservice/build/libs/myservice.jar!/BOOT-INF/lib/spring-cloud-sleuth-zipkin-3.0.2.jar!/org/springframework/cloud/sleuth/zipkin2/ZipkinProperties.class

The class hierarchy was loaded from the following locations:

    org.springframework.cloud.sleuth.zipkin2.ZipkinProperties: jar:file:/.../code/services/myservice/build/libs/myservice.jar!/BOOT-INF/lib/spring-cloud-sleuth-zipkin-3.0.2.jar!/

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.cloud.sleuth.zipkin2.ZipkinProperties`

**Comment by jimshowalter** [comment]
Does that whether implementation("org.springframework.cloud:spring-cloud-sleuth-autoconfigure:${sleuthVersion}") is commented out or uncommented.

**Comment by jonatan-ivanov** [comment]
You can either use `sleuth-zipkin` (brave) or `sleuth-otel` you need to choose which one.

If you want to use Zipkin(Brave) (recommended in prod): https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/#how-to-set-up-sleuth-with-brave-zipkin-http
If you want to use OTel (not recommended in prod): https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel#quick-start

I'm closing this issue because of this, if I misunderstand something please let me know and I can reopen it.

**Comment by jimshowalter** [comment]
We excluded brave. We only want what's compatible with otel. We don't seem to be able to achieve that.

**Comment by jonatan-ivanov** [comment]
I saw you excluded brave but you included `org.springframework.cloud:spring-cloud-sleuth-zipkin` :)

If you take another look at https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel#quick-start you will see these:
```
spring-boot-starter-web
spring-cloud-starter-sleuth; exclude: spring-cloud-sleuth-brave
spring-cloud-sleuth-otel-autoconfigure
```
zipkin is not there and it should not be, you should either use Zipkin (Brave) or OTel, the two does not work together.
A not very good but somewhat similar example for this could be: you need to decide if you use log4j or logback for logging.

**Comment by huggsboson** [comment]
Hi @jonatan-ivanov: I just want to say thank you for your quick and patient responses!

I think we must have gotten confused by this doc page:
https://spring-cloud-incubator.github.io/spring-cloud-sleuth-otel/docs/current/reference/html/howto.html#how-to-set-up-sleuth-with-otel-zipkin-http

If you confirm those are in error we can file an issue over there to fix it up.

Just for some context, we're late/early adopters of distributed tracing at our company, and were trying to hop onto the OTeL train to avoid having to switch to another set of libs / headers later.  So we were gonna try an push through the growing pains associated with adopting OTel / W3C headers.  What we're running into here is we'd like to use:
1. W3C headers for context prop
2. Short term export to a zipkin collector for demo purposes.

I was under the impression that the otel libs would likely support zipkin exports, but maybe the current sleuth-otel doesn't support zipkin exports.  I'm curious if the standard sleuth libs support extraction/injection of the W3C headers.

Thanks again so much for all your help.

**Comment by jonatan-ivanov** [comment]
Hi @huggsboson
Oh, I see what you are trying to do. Using `opentelemetry-exporter-zipkin` should work but right now it makes less sense to me because:
- Sleuth-OTel and OTel are not prod ready
- Brave is created by the Zipkin community, it has great Zipkin support
- Sleuth abstracts the instrumentation library (Brave or OTel) away, you can switch between them

Right now, I would not go to prod with OTel.
If you want to, could you please try two things?
1. Do not define versions for libraries (`sleuthVersion`), just use BOM (`springCloudReleaseTrainVersion`)
2. Add `opentelemetry-exporter-zipkin` as you see in the docs: https://spring-cloud-incubator.github.io/spring-cloud-sleuth-otel/docs/current/reference/html/howto.html#how-to-set-up-sleuth-with-otel-zipkin-http


Oh wait, I just realize that the docs does not contain `opentelemetry-exporter-zipkin` for gradle, it is only there for maven:
```
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${releaseTrainVersion}"
        mavenBom "org.springframework.cloud:spring-cloud-sleuth-otel-dependencies:${springCloudSleuthOtelVersion}"
    }
}

dependencies {
    implementation("org.springframework.cloud:spring-cloud-starter-sleuth") {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-sleuth-brave'
    }
    implementation "org.springframework.cloud:spring-cloud-sleuth-otel-autoconfigure"
    implementation "org.springframework.cloud:spring-cloud-sleuth-zipkin"
}
```

Could you please try this out any let me know if it works, I'm going to fix the docs accordingly.

**Comment by jimshowalter** [comment]
Per your earlier comments, aren't these incompatible?:

    implementation "org.springframework.cloud:spring-cloud-sleuth-otel-autoconfigure"
    implementation "org.springframework.cloud:spring-cloud-sleuth-zipkin"

**Comment by jimshowalter** [comment]
Thank you for all of your help. We have it working!

Now we'd like to selectively enable it, so it only runs in local and dev, not in staging or prod.

But when I tried moving the config to application-dev.yaml (and not in local) that didn't keep it from trying:

`
(I/O error on POST request for "http://localhost:9411/api/v2/spans": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused))
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9411/api/v2/spans": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)
        at org.springframework.cloud.sleuth.zipkin2.ZipkinRestTemplateWrapper.doExecute(ZipkinRestTemplateWrapper.java:69)
`

Is there a way to selectively enable sleuth output?

**Comment by jonatan-ivanov** [comment]
I got confused about your use case (I thought you want to use OTel with OTLP), sorry for the miscommunication about this, let me explain what is going on under the hood:
- Sleuth abstracts away the tracing libraries, it supports *Brave* and *OTel* but you need to choose which one do you want to use, they won't work together (that's why you need to exclude *Brave* if you use *OTel*)
- Brave can export spans (`sleuth-zipkin`)
- OTel has a bunch of [exporters](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters), their own protocol called OTLP but they support Zipkin too that's where you need `sleuth-zipkin` (this is where I misspoke above, sorry about it)

I'm glad it works, could you please share what was the issue? I would like to use that feedback to improve our docs (or auto-configuration). (fyi: https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/commit/0042954d552b9428b90f11df91305392e52283c6)

You should be able to disable exporting spans to Zipkin using the `spring.zipkin.enabled`. If it works if you put it in `application.yml` but it does not work in `application-dev.yml` most probably spring is using 
the default profile and not the dev profile. At startup you can see which profile is used in the logs.

**Comment by jimshowalter** [comment]
Primarily the issue was that we really wanted to use opentelemetry, but it's not ready yet, and I didn't listen to you quickly enough.

Regarding the disable, it works fine. The problem was precedence. I moved some yaml files around and now it defaults to off, but can be enabled per environment.

Thank you for your multiple quick responses!

**Comment by jonatan-ivanov** [comment]
Glad you got it working, closing the issue.
