### ISSUE TITLE
how to use RSocket with Spring Cloud Sleuth?

### ISSUE THREAD

**Issue by nikita111100** [spring-cloud/spring-cloud-sleuth#1981]
If i add your dependency and send a request to another service i see this:

![rsocket](https://user-images.githubusercontent.com/50965855/122727004-9f4d6700-d287-11eb-800b-087f196a0714.png)

I use RSocket.
Maybe I need to configure a bean? 

Version:
Spring Cloud Sleuth v3.0.3 (latest)
Spring boot 2.5.0 

Thanks for you reply.

**Comment by marcingrzejszczak** [comment]
Dear @nikita111100 , you're filing a lot of issues when you should be asking questions on Gitter or Stackoverflow. Please read carefully the resolution details of the issue https://github.com/spring-cloud/spring-cloud-sleuth/issues/1677 . You will notice that the version for which this is merged is `3.1.0-M1` and since it's not released you'd need to use `3.1.0-SNAPSHOT`.
