### ISSUE TITLE
Sleuth Samplers documentation?

### ISSUE THREAD

**Issue by jorgegueyer** [spring-cloud/spring-cloud-sleuth#2019]
Hello,

I am using Spring Cloud Sleuth with its version: 2.2.8.RELEASE. I would like to know if it exists any kind of documentation about Sleuth Samplers. I am using Sampling but I haven't found anything about that kind of samplers exist or how to work.

Thanks for your time.

**Comment by jonatan-ivanov** [comment]
Have you found the official docs?
Sleuth 2.x is using Brave under the hood: [2.2.x docs about Sampling](https://docs.spring.io/spring-cloud-sleuth/docs/2.2.x/reference/html/#sampling)
Sleuth 3.x abstracts away the Tracing libraries and using Brave by default: [3.1.x docs about Sampling](https://docs.spring.io/spring-cloud-sleuth/docs/3.1.x/reference/html/project-features.html#features-sampling)

Since in both cases the sampling decision is the responsibility of the Tracing library, you can find these details there:
[Brave's docs about Sampling](https://github.com/openzipkin/brave/tree/master/brave#sampling)
If you want to know what are the different samplers available in Brave, check the implementations of the [`Sampler`](https://github.com/openzipkin/brave/blob/5be287b91c3d18da9fc7a597d71b12b27be6043c/brave/src/main/java/brave/sampler/Sampler.java#L28) abstract class, most of them are in the [`brave.sampler` package](https://github.com/openzipkin/brave/tree/master/brave/src/main/java/brave/sampler) but your IDE will be more helpful in this search, here are some:
- `brave/src/main/java/brave/sampler/BoundarySampler.java`
- `brave/src/main/java/brave/sampler/CountingSampler.java`
- `brave/src/main/java/brave/sampler/DeclarativeSampler.java`
- `brave/src/main/java/brave/sampler/RateLimitingSampler.java`
- `brave/src/main/java/brave/sampler/ParameterizedSampler.java`
- `instrumentation/http/src/main/java/brave/http/HttpSampler.java`
- `instrumentation/rpc/src/main/java/brave/rpc/RpcRuleSampler.java`
- `instrumentation/http/src/main/java/brave/http/HttpRuleSampler.java`
- `instrumentation/messaging/src/main/java/brave/messaging/MessagingRuleSampler.java`

I'm closing this issue, please let us know if this does not answer your question so that we can reopen this issue.
