### ISSUE TITLE
Instrumentation of `ThreadPoolTaskScheduler` does not work with `ExecutorServiceMetrics`

### ISSUE THREAD

**Issue by poznachowski** [spring-cloud/spring-cloud-sleuth#2020]
Hello.
I wanted to take advantage of recent addition to Spring Boot - automatic registration of executor services metrics, that was [added recently](https://github.com/spring-projects/spring-boot/commit/f8555b9071878890e940cd18a2ae3ce44661d841).

We have our executor services wrapped automatically for distributed tracing. All seems to be working fine except for `ThreadPoolTaskScheduler` tracing which always gives "NaN" values:

`http://www.localhost:8080/actuator/metrics/executor.pool.core?tag=name:pubsubSubscriberThreadPool` :

```
{
  name: "executor.pool.core",
  description: "The core number of threads for the pool",
  baseUnit: "threads",
  measurements: [
    {
      statistic: "VALUE",
      value: "NaN"
    }
  ],
  availableTags: [ ]
}
```

with sleuth async tracing disabled it works fine:

```
{
  name: "executor.pool.core",
  description: "The core number of threads for the pool",
  baseUnit: "threads",
  measurements: [
    {
      statistic: "VALUE",
      value: 4
    }
  ],
  availableTags: []
}
```

Spring Boot 2.6.0.M2, Spring Cloud 2021.0.0-M1

Sample project is avaiable at: https://github.com/poznachowski/sleuth-executor-metrics-sample
Sample provides `ThreadPoolTaskScheduler` instance in same manner as [GcpAutoConfiguration](https://github.com/spring-cloud/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java#L134) version, which we are using.

I was also able to check, how [opentracing](https://github.com/opentracing-contrib/java-spring-cloud/blob/master/instrument-starters/opentracing-spring-cloud-core/src/main/java/io/opentracing/contrib/spring/cloud/async/ExecutorBeanPostProcessor.java) behaves. It looks fine.

**Comment by marcingrzejszczak** [comment]
Hi! I've cloned your code, executed `http://www.localhost:8080/actuator/metrics/executor.pool.core?tag=name:pubsubSubscriberThreadPool` and got this json back

```json

{
  name: "executor.pool.core",
  description: "The core number of threads for the pool",
  baseUnit: "threads",
  measurements: [
    {
      statistic: "VALUE",
      value: 4
    }
  ],
  availableTags: []
}


```

**Comment by poznachowski** [comment]
I did some more digging and here are my findings about the issue.
Indeed sometimes value is accurate, but it looks like it depends on the GC and clearing out the `WeakReference` in the `DefaultGauge` [implementation](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultGauge.java#L51).

As you see on the screens below when the reference is available it's of `LazyTraceScheduledThreadPoolExecutor` instance and the 4 is returned, but when the `WeakReference` is gone I get NaN.

![Screenshot 2021-09-22 at 23 27 11](https://user-images.githubusercontent.com/1326077/134495169-ad6a46c1-6b90-48ec-a8eb-f347c835f5e7.png)
![Screenshot 2021-09-22 at 23 27 45](https://user-images.githubusercontent.com/1326077/134495255-3cbe5cfb-7068-4a5d-8278-2cd53e831903.png)

Not sure it is relevant and it may be a coincidence, but I always got NaN on JDK 14.0.1 I sometimes got "4" on JDK 11.0.9.1.

**Comment by marcingrzejszczak** [comment]
cc @jonatan-ivanov :point_up:

**Comment by jonatan-ivanov** [comment]
@poznachowski _Part of_ what you are experiencing is expected: the `Gauge` does not want to prevent objects being garbage collected so it uses a `WeakReference` to refer to its state object. This means that if there is no reference pointing to the state object (in this case Sleuth's `LazyTraceScheduledThreadPoolExecutor`), that object gets garbage collected.

So whoever registers the `Gauge`, needs to ensure to keep a strong reference to the state object which brings us to the unexpected part of the issue: why the `LazyTraceScheduledThreadPoolExecutor` is getting garbage collected?

I was able to repro the issue running the app from IntelliJ with Java 17 (`17+35`), Java 11 (`11.0.12+7`), and Java 8 (`1.8.0_302`) (Temurin/Adoptium/AdoptOpenJDK) by triggering a GC from VisualVM. Interestingly, I was able to repro it with 11 without manual GC but after a while this did not work and I needed to manually trigger a GC (I think it is the weather 😄).

It seems the issue lies in the Sleuth instrumentation logic. It seems during the instrumentation lots of `LazyTraceThreadPoolTaskScheduler` instances are created, e.g.: if I inject a `ThreadPoolTaskScheduler` into a controller, I get an instance of `LazyTraceThreadPoolTaskScheduler` and every time I invoke a method on this instance (e.g.: `toString`), a new `LazyTraceThreadPoolTaskScheduler` is created.

In the case of the Micrometer instrumentation, every call to [`taskScheduler.getScheduledThreadPoolExecutor()`](https://github.com/spring-projects/spring-boot/blob/528ced4f0daf98f58b63cbac097a14e15eb0e0e5/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/task/TaskExecutorMetricsAutoConfiguration.java#L91) results in a new instance of `LazyTraceScheduledThreadPoolExecutor`. Since these are throwaway objects, nothing refers them so they got garbage collected which causes the behavior you experience.
