### ISSUE TITLE
No qualifying bean of type 'org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter' available

### ISSUE THREAD

**Issue by Jojoooo1** [spring-cloud/spring-cloud-sleuth#2027]
**Describe the bug**
After upgrading from spring 2.4.9 to 2.5.4 I started to get `No qualifying bean of type 'org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter' available` 

It seems that TracingFilter can not be injected anymore.

**Sample**
```
@ExtendWith(SpringExtension.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@SpringBootTest(classes = Application.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class YourControllerIT {

	@Autowired
	private WebApplicationContext context;
	private MockMvc mockMvc;

	@Autowired
	private TracingFilter traceFilter;

	@BeforeAll
	void init() throws IOException, URISyntaxException {
		this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context).apply(springSecurity())
				.addFilters(this.traceFilter)
				.build();
	}
}
```

**Comment by marcingrzejszczak** [comment]
Yes, we can't register as a bean anymore because we would register it twice. We're registering it here - https://github.com/spring-cloud/spring-cloud-sleuth/blob/main/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/web/TraceWebServletConfiguration.java#L75-L82 via a `FilterRegistrationBean`. You can use the factory method to create it yourself https://github.com/spring-cloud/spring-cloud-sleuth/blob/main/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/servlet/TracingFilter.java#L46-L48
