### ISSUE TITLE
traceId and spanId are not displayed immediatly in restcontroller logs

### ISSUE THREAD

**Issue by nkhalis** [spring-cloud/spring-cloud-sleuth#2175]
Hello,

I noticed that some logs were not tagged with spanId and traceId. I investigated and I think that there is a potential bug.
Here is my RestController which calls the method delete reservation. The latter displays some logs.
<img width="1506" alt="Capture d’écran 2022-06-08 à 09 32 10" src="https://user-images.githubusercontent.com/70886167/172561279-9d385f32-d1d6-49d7-ae20-e45c46bb2358.png">

The deleteReservation method:
<img width="1205" alt="Capture d’écran 2022-06-08 à 09 31 28" src="https://user-images.githubusercontent.com/70886167/172561544-95730042-35f9-4ab1-94c6-0a33ca8ed5e9.png">

And the logs:
<img width="1600" alt="Capture d’écran 2022-06-08 à 09 31 16" src="https://user-images.githubusercontent.com/70886167/172562899-afdfccfd-785b-4cc2-b2ce-b42df81acaa5.png">

You can see that the first logs don't have spanId nor traceId (mark with "?"), and after few time, the logs are displayed with them correctly.

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by nkhalis** [comment]
Thanks for your response, I'm going to provide it

**Comment by nkhalis** [comment]
Hello,

I figured out that there was a conflict between an other Brave lib which add tags to the logs and delete the spanId and traceId.
Sorry for the trouble...
