### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-sleuth#22]
Sleuth was kind of off the cuff.  Maybe spring-cloud-trace?

**Comment by dsyer** [comment]
I'm easy. We have "actuator" in Boot which is kind of abstract as well. Feel free to rename it "trace" if you like.

**Comment by spencergibb** [comment]
Closing as both @dsyer and @mstine gave a thumbs up.  I kind of like it too.

**Comment by shakuzen** [comment]
@spencergibb @dsyer 
I know this issue is closed, but if I am to put my two cents in, between the two proposed options I would vote for `spring-cloud-trace`. For many non-native English speakers, `sleuth` and `actuator` are not familiar words whereas `trace` would be familiar to almost anyone working in a field that would use this project. I understand project names often use words like this (just looking at the list of Apache projects, it isn't clear what most of them do - i.e. Mesos, Aurora, Kafka), but I think it might help adoption and recognition rates (at least initially) to have a more easily understandable name - especially for non-native English speakers. I know at my company I've had to repeatedly remind people what the Actuator project is and what it does.

**Comment by spencergibb** [comment]
@shakuzen thanks.  We're going to think about this some more.

**Comment by dsyer** [comment]
Too many people like it as "sleuth". I guess it's just going to be a conversation topic for non-English speakers.
