### ISSUE TITLE
slf4j (logback) logs not getting forwarded to open-telemetry-collector

### ISSUE THREAD

**Issue by ff-sdesai** [spring-cloud/spring-cloud-sleuth#2253]
I have created a spring-boot micro-service with spring-cloud-sleuth. I have also configured a open-telemetry-collector to forward the logs to datadog. The otel-collector is running in a docker container along with the micro-service. I have used logback-appender to forward the logs also to otel-collector along with traces. However, in datadog, I can only see traces and not logs. The logs printed are using the same traceId and spanId as that of trace.
This issue can be reproduced using a POC with very few files and is uploaded at [https://github.com/ff-sdesai/distributed-tracing-spring](https://github.com/ff-sdesai/distributed-tracing-spring). The readme.md has the steps to run the application. You will need to enter a valid datadog API key in the .env file.I will not be able to share the key since the key is specific to my organization.  
Please let me know if there is something else that I should specify along with these details.

**Comment by jonatan-ivanov** [comment]
>However, in datadog, I can only see traces and not logs.

Since Sleuth is a solution for distributed tracing, as far as I can see everything works fine from Sleuth's perspective, not having logs in datadog with the OTel collector/appender should be an issue outside of Sleuth.

Please let us know if this is not the case.

(Also, as far as I can see your reproducer has lots of files, it definitely does not seem a minimal project to me.)
