### ISSUE TITLE
jdbc instrumentation: with p6spy connection span sometimes does not close

### ISSUE THREAD

**Issue by alex-kormukhin** [spring-cloud/spring-cloud-sleuth#2254]
**Describe the bug**
Sleuth 3.1.5.

For constructions

```
        try (Stream<Some> stream = jdbcTemplate.queryForStream("select * from SOME", (rs, rowNum) -> new Some(rs));) {
            return stream.collect(Collectors.toList());
        }
```

with p6spy proxy, connection span does not close.

![image](https://user-images.githubusercontent.com/99888299/214294776-4aa1d5bb-6803-4410-8851-ce49b53debfe.png)
There is no connection span and result-set span has warning "invalid parent span".

With datasource-proxy all correct:
![image](https://user-images.githubusercontent.com/99888299/214296314-a0b927ad-27b5-4ee2-b9bc-54b01471dace.png)

This is because [queryForStream obtain connection with stmt.getConnection()](https://github.com/spring-projects/spring-framework/blob/114d6a925639d9c1194c8a7562381001633a3820/spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java#L484) but [p6spy StatementWrapper simple delegate getConnection to underlying statement](https://github.com/p6spy/p6spy/blob/1df6b39048f97af29ff3b1c1b245f59d7d0051bc/src/main/java/com/p6spy/engine/wrapper/StatementWrapper.java#L380), thus underlying connection closed, but not p6spy connection wrapper and [sleuth afterConnectionClose](https://github.com/spring-cloud/spring-cloud-sleuth/blob/28fba56212d4afecae31e359bf8794cb819d90df/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceListenerStrategy.java#L408) is never called.

**Comment by marcingrzejszczak** [comment]
cc @ttddyy (I don't think we'll have the problem with the jdbc-observations because we're not using p6spy there)

**Comment by ttddyy** [comment]
Thanks for the nudge.

Yes. The root cause of this issue is that p6spy returns the connection from the delegate, which is not the p6spy wrapped or proxied connection as @alex-kormukhin described.

https://github.com/p6spy/p6spy/blob/1df6b39048f97af29ff3b1c1b245f59d7d0051bc/src/main/java/com/p6spy/engine/wrapper/StatementWrapper.java#L380

In datasource-proxy, it handles `Statement#getConnection` to return the proxy `Connection`.

https://github.com/jdbc-observations/datasource-proxy/blob/9601ff0aaf6adb2d36e0a056f786dcdba021bc8c/src/main/java/net/ttddyy/dsproxy/proxy/StatementProxyLogic.java#L168-L171

Hence, when spring closes the `Connection`, it is a proxy connection and it triggers a datasource-proxy callback that closes the span.

https://github.com/spring-projects/spring-framework/blob/114d6a925639d9c1194c8a7562381001633a3820/spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java#L488

So, should not be a problem for datasource-proxy based implementation.

**Comment by marcingrzejszczak** [comment]
Since p6spy is [no longer maintained](https://github.com/p6spy/p6spy/issues/541) I guess there's nothing we can do about this other than suggest to use the datasource proxy project :shrug:
