### ISSUE TITLE
SpanInjector/SpanExtractor for Feign are not overridable

### ISSUE THREAD

**Issue by KamikaZeeFu** [spring-cloud/spring-cloud-sleuth#265]
According to the docs, custom trace-id/span-id header names can be set via registering new @Primary Injectors/Extractors for the required type.

However, in ```TraceFeignClientAutoConfiguration``` these classes are not registered as beans, but rather constructed via private methods.
This makes it impossible to use custom header names with Feign.

As a general remark, if you just want to change the used header names you have to override a bunch of beans, which feels pretty clunky. Exposing them via ```@ConfigurationProperties``` makes for a more user friendly configuration.

**Comment by marcingrzejszczak** [comment]
Hi! With Feign that was done deliberately cause the solution there is hacky to say the least. We need to rewrite stuff in Feign https://github.com/spring-cloud/spring-cloud-sleuth/issues/202 and then we can open things up. 

We are aware about the problems related to using custom header names. For the first release of Sleuth we've decided to focus more on the stability of the solution rather than ease of configurability. For sure we'll address this issue in subsequent releases, especially since there's the Baggage bit to be done: https://github.com/spring-cloud/spring-cloud-sleuth/issues/143 https://github.com/spring-cloud/spring-cloud-sleuth/issues/237
