### ISSUE TITLE
More generic id for traces and spans

### ISSUE THREAD

**Issue by jorgenota** [spring-cloud/spring-cloud-sleuth#266]
Hi,

At our organization we'd like to integrate apps using this project with other technologies. We've been asked to use an UUID as in [http://docs.oracle.com/javase/7/docs/api/java/util/UUID.html](UUID). An UUID is unique and generators exist for different technologies... and we're using it with other technologies.

I've been looking at different repositories and issues and I've noticed that:
- Issue #106 changed from String (representing an UUID) to a long. It doesn't explain why but I guess it's because zipkin uses that format, right?
- Issue #19 includes a comment saying: "64 bits is really too small and Zipkin admits it"... Are 64bits enough?
- OpenTracing project defines a Span in a very generic way: https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/Span.java

Are you sure you want to define a Span as a class containing long fields for trace and span ids? Would it be possible to define Span in a more generic way? For example:
* Define Span as a parametrizable class/interface and provide a default implementation using Long for the ids. I don't know, maybe sth like "DefaultSpan extends Span<Long>".
* Or define an extensible SpanId class/interface as field for the ids.
* Or sth more generic as using a String (like you were using before) for the ids.

**Comment by adriancole** [comment]
the zipkin admits it thing might be a bit varied. Twitter receives more traffic than most sites and collisions have been noted, but they still use the same format today. There are other very large sites that also use this id structure.

Since ids are unique on trace id + span id, you get effectively 128 bits of uniqueness, just like htrace etc.

Are you running into collision problems? What sort of trace volume do you have?

**Comment by adriancole** [comment]
To comment on the other points..

OpenTracing is an interface, and doesn't say anything about how ids are made or even if they exist. That's to allow different implementations, such as sleuth, to exist underneath the api. If they specified an ID format, it would likely interfere with the api goal.

Sleuth, on the other hand, is an implementation. You'll notice it has a lot of instrumentations baked in, and it takes care to make sure everything works. For this reason, we have to be careful about where volatility is introduced.

It was intentional to limit choices on IDs, not just from a technology soundness pov, but it also helps us remain compatible with other zipkin traces. IOTW, given the structure as it is, sleuth traces are explicitly compatible with those written in various languages. http://zipkin.io/pages/existing_instrumentations.html

ps if the goal is to correlate, you can always log your UUID in the span. ex. "request.id"=YOUR_UUID

zipkin will allow you to query against that. It is common to log keys such as this.

**Comment by jorgenota** [comment]
We aren't using Sleuth on production so we haven found collision problems yet. UUID gives us more guarantees and besides from our organization they are asking for that format, that's why we are asking for this "improvement".

Thank you for your answers and suggestions, Adrian.

**Comment by adriancole** [comment]
No prob

**Comment by marcingrzejszczak** [comment]
We can't actually add this again as an improvement for all the reasons that Adrian has mentioned. 

What you can do is as Adrian says

> log your UUID in the span

then you can for example implement your own version of a logger and put that UUID into MDC to log it into the logs.

Is this solution acceptable for you?

**Comment by jorgenota** [comment]
It's not just logging the info of the UUID received from "legacy clients" but the capability of using UUID as the trace and span ids along all the requests.

I'll check with the other colleages involved with all this information to see if it's acceptable, I think Sleuth is a very interesting project to use in our Java apps.

Thanks again.

**Comment by marcingrzejszczak** [comment]
Ping :) So how did your discussions go?

**Comment by jorgenota** [comment]
It seems we'll give it a try as it is at the moment, using the 64bits randomly generated ids :)

**Comment by marcingrzejszczak** [comment]
Cool! :) I'm closing it then
