### ISSUE TITLE
Pass trace data via @HystrixCommand

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-sleuth#39]

**Comment by spencergibb** [comment]
See https://github.com/Netflix/Hystrix/issues/92#issuecomment-12848797

**Comment by morfeo8marc** [comment]
I've read the issues, and also taken a look at your extension of HistrixCommand. What is the purpouse of this extension?

What should be use on combimatiom with @HistrixCommamd to allow tracing happen? Should a custom concurrent strategy be implememted?

**Comment by spencergibb** [comment]
@morfeo8marc the purpose of the extension is to use is when you construct a `HystrixCommand` by hand. This issue is to support passing trace data via `@HystrixCommand`.

**Comment by dnathanson** [comment]
Just ran into this issue.  :+1:

**Comment by dnathanson** [comment]
When this is implemented, will it handle the case where Hystrix isolation policy is THREAD?  I tried using extending TraceCommand instead of annotating with @HystrixCommand and while it does create a span, the trace context is not passed to Hystrix's child thread so the parent/child relationship between spans is lost.

**Comment by swehner** [comment]
The workaround of using a custom ConcurrencyStrategy works for this case:
```
hystrix.plugin.HystrixConcurrencyStrategy.implementation=SpanPreservingConcurrencyStrategy
```
This would be the implementation:
```
public class SpanPreservingConcurrencyStrategy extends HystrixConcurrencyStrategy {
	@Override
	public <T> Callable<T> wrapCallable(Callable<T> callable) {
		return new SpanPreservingCallable<T>(callable);
	}
	
	public static class SpanPreservingCallable<T> implements Callable<T> {
		private Span currentSpan;
		private Callable<T> callable;

		public SpanPreservingCallable(Callable<T> callable) {
			this.callable = callable;
			this.currentSpan = TraceContextHolder.getCurrentSpan();
		}
		
		@Override
		public T call() throws Exception {
			// set span of the calling thread
			TraceContextHolder.setCurrentSpan(currentSpan);
			try {
				return callable.call();
			} finally {
				// reset span
				TraceContextHolder.setCurrentSpan(null);
			}
		}
	}
}
```
I've tried to make this more extensible so it could be included in spring-cloud-netflix, but I've encountered several problems as this class is instantiated by Hystrix and not by Spring...

**Comment by spencergibb** [comment]
Thanks!

**Comment by adriancole** [comment]
Good point that hystrix needs to propagate data. It is probably also
helpful to actually start a span for each hystrix command. As tracing is
primarily for service boundaries, hystrix makes tons of sense.

Ex hystrix instrumentation tostart a new span with hystrix's command name
as the span name, and the command group as a tag.

**Comment by swehner** [comment]
I agree, one question though: How would this work if the HystrixCommand does a network call? In that case you'd end up with 2 spans which might be overkill?

**Comment by adriancole** [comment]
This is intentional. So firstly hystrix should be much better named than
any network calls within it. Ex. searching for hystrix command name should
make more sense than searching for "get".
It could be multiple calls, or no calls! This is in ideal node in the
graph, in other words, if its purpose is explaining latency and
troubleshooting.

**Comment by adriancole** [comment]
Here's more stuff that might not be obvious:

Say you were troubleshooting a problem, and you have Hystrix
Dashboard, and zipkin's UI. Much easier if you can correlate (or even
link) one to another precisely!

Zipkin's UI is in tree form, and you can collapse nodes. You'd get
sensibly named nodes for the commands, you can "opt-in" to seeing
details of which network calls, if any were under it, by clicking +,
or you can hide by clicking -

This collapsing support is needed anyway as existing sites have
hundreds of spans per trace due to fan-out.

**Comment by adriancole** [comment]
Here's a collapsing example, the UI is trained to expand only nodes involving a service is involved in, "lorem" in this case. I clicked on collapse all, and then clicked on "lorem" which expanded paths to it.

<img width="1198" alt="screen shot 2015-11-13 at 7 56 04 am" src="https://cloud.githubusercontent.com/assets/64215/11150258/10fa0f84-89dc-11e5-83c2-88a8b9db8e27.png">

Then, I clicked "vitae" which had multiple paths.

<img width="1212" alt="screen shot 2015-11-13 at 7 58 28 am" src="https://cloud.githubusercontent.com/assets/64215/11150326/5fcaa2d6-89dc-11e5-8704-6c0fce4a8b4c.png">

**Comment by marcingrzejszczak** [comment]
The solution from  @swehner  seems like a good idea. The only problem I see is when someone already has a custom strategy.

**Comment by marcingrzejszczak** [comment]
@spencergibb , @dsyer , @adriancole In this commit I've done an initial approach with a test that I guess proves that it's working - https://github.com/spring-cloud/spring-cloud-sleuth/commit/6ecfbca6ed6bcd38e715f03ca5d5a513c9593346 . WDYT about this?

**Comment by marcingrzejszczak** [comment]
Done here - https://github.com/spring-cloud/spring-cloud-sleuth/pull/78
