### ISSUE TITLE
feignClient with URL defined, wraps client with LoadBalancer

### ISSUE THREAD

**Issue by mikesarver** [spring-cloud/spring-cloud-sleuth#393]
When Slueth is on the classpath,  a FeignClient with a url defined is trying to resolve the host using LoadBalancer:DynamicServerListLoadBalancer.  The issue does not happen if spring.sleuth.feign.enabled=false
It appears that TraceFeignClient is being created with a loadBalancer delegate.

The issue can be reproduced in the following project.  It does assume eureka is running on localhost:8761 
https://github.com/mikesarver/demo-feign-uri

**Comment by marcingrzejszczak** [comment]
OK I've managed to debug this. The thing is that with and without Sleuth the `LoadBalancerFeignClient` is created. Which is not bad. The problem is that in this particular case the `SynchronousMethodHandler` from Feign has the `LoadBalancerFeignClient` injected instead of the `Default` one. 

> It appears that TraceFeignClient is being created with a loadBalancer delegate.

We're wrapping all Feign's clients into the trace representation. So there's the default one and the load balancer one. Both of them are wrapped. I have to yet analyze why the load balanced one gets injected where it shouldn't.

**Comment by marcingrzejszczak** [comment]
It turned out that in SC-Netflix 1.2.0 the `FeignClientFactoryBean` is using an instanceof to check whether the load balancer is of proper type. SInce we were doing delegation in Sleuth the type was wrong.

**Comment by marcingrzejszczak** [comment]
Of course @mikesarver  it would be assume if you could confirm that it's working :)

**Comment by mikesarver** [comment]
I conformed this resolves the issue in the project.  Thank you for the quick resolution.

**Comment by marcingrzejszczak** [comment]
Thanks for checking :)

**Comment by marcingrzejszczak** [comment]
oh and BTW you've become a hero of one of my tests ;) https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/issues/issue393/Issue393Tests.java#L75
