### ISSUE TITLE
Different pieces of information: HystrixTraceCallable vs TraceCommand

### ISSUE THREAD

**Issue by C-Otto** [spring-cloud/spring-cloud-sleuth#405]
According to the [documentation](http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_hystrix) there are (at least) two ways to use Sleuth with Hystrix in a Spring setting.

The first is done automatically, and forwards the trace/span context information into new threads created/used by Hystrix.

The second is done manually, by using `TraceCommand` instances instead of `HystrixCommand` instances (where you'd need to provide a `Tracer` instance, which I was struggling with in #402).

Both approaches solve the issue of passing thread-local information to other threads. However, there seems to be a difference in the actual information provided to consumers of Sleuth (e.g. logs, Zipkin):

 - The wrapper creating `HystrixTraceCallable` instances continues existing spans, i.e. Hystrix calls resulting out of a MVC REST endpoint invocation count as part of the span created for the REST endpoint.
 - The `TraceCommand` implementation explicitly creates a new span, unconditionally. As a result, the Hystrix command invocation is clearly visible in Zipkin.

I love the details I get when using `TraceCommand`, but I'd prefer the magic from `HystrixTraceCallable`. 

Why are the results different? Is there a reason I don't see? What exactly are those differences? How can I get the best out of both worlds?

Thank you!

**Comment by marcingrzejszczak** [comment]
That's a very good question :) There are two aspects:

== Known vs unknown caller

So the problem with magic is that you don't know a lot of things when you use it. All the aspects / interceptions etc. are done at some moment in time. You have no idea who called that code, why and who will execute that code later on.  When using the Sleuth Hystrix automatic solution we came to the conclusion that we will reuse whatever you do.  That makes sense since all the automated solutions can't automatically set all the detailed information.

== We know better ;)

It's closely related to this https://github.com/spring-cloud/spring-cloud-sleuth/issues/180 . Initially we came to the conclusion that we know better than the user does and we have started automatically spans in the user's stead. That's why `HystrixTraceCallable` creates a new span. That's not the best of choices and for the next major release we will remove such an approach. We should always continue a span and create a new one only if there wasn't a previous one. The thing is that if you want a custom span for the "magical" Hystrix wrapping just use Hystrix as usual and create a span yourself

Pseudocode:

```
@Autowired Tracer tracer;

new HystrixCommand() .... {
    Span span = tracer.createSpan("my_custom_span");
    try {
     // do sth
    } finally {
       tracer.close(span);
    }
}
```

Hopefully it answers your question :)

**Comment by C-Otto** [comment]
I just found https://github.com/spring-cloud/spring-cloud-sleuth/issues/39#issuecomment-156463278 which already pointed to this.

I think you didn't mean `HystrixTraceCallable` in the `We know better` part of your comment?

Anyway, I now understand the issue and the motivation, and also see valid solutions. Thank you, feel free to close the issue!

**Comment by marcingrzejszczak** [comment]
Of course I meant the `TraceCommand` - I'm updating my comment
