### ISSUE TITLE
Host in endpoint collected from Cloud Foundry app is not helpful

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#41]
Tends to be 127.0.0.1:98723

**Comment by dsyer** [comment]
On the other hand, there is probably no better value to be had. We know the service name (which is all you really need in Cloud Foundry), and the IP/port information is really not adding anything. If we could make it a `String` instead of an `Address` we could maybe do something more informative (the space id or something), but Zipkin mandates the IP address, so there's not much we can do if we want to have the option of using Zipkin.

**Comment by adriancole** [comment]
you could put 0 for the ip and port when there is no valid value.

I think serviceName will eventually migrate to a tag, like below. Ex
sleuth could choose to use tags instead of endpoints now, and just put
0 if there's no ipv4 or port.

https://github.com/opentracing/opentracing-python/blob/master/opentracing/ext/tags.py

# PEER_SERVICE records the service name of the peer
PEER_SERVICE = 'peer.service'
# PEER_HOSTNAME records the host name of the peer
PEER_HOSTNAME = 'peer.hostname'
# PEER_HOST_IPV4 records IP v4 host address of the peer
PEER_HOST_IPV4 = 'peer.ipv4'
# PEER_HOST_IPV6 records IP v6 host address of the peer
PEER_HOST_IPV6 = 'peer.ipv6'
# PEER_PORT records port number of the peer
PEER_PORT = 'peer.port'

**Comment by adriancole** [comment]
by "and just put 0 if there's no ipv4 or port."

I mean.. say sleuth chooses to use tags to document the peer (or its
local) serviceName.

When it comes time to convert to zipkin, it would look for
local.serviceName and stuff that into zipkin.Endpoint.serviceName. if
it fails to find local.ipv4, then it would put 0 for
zipkin.Endpoint.ipv4

I've not thought the "tags" bit through, but I'm pretty sure that 0
will work for ip and port (eventhough clock skew might not work
without ips)

**Comment by adriancole** [comment]
Update on this issue, starting with Zipkin 1.4 endpoints can omit IPv4 (by setting Endpoint.ipv4 to 0), and optionally log Endpoint.ipv6 as the raw 16byte address.

**Comment by marcingrzejszczak** [comment]
This will be solved by https://github.com/spring-cloud/spring-cloud-sleuth/issues/369

**Comment by marcingrzejszczak** [comment]
Fixed by #369
