### ISSUE TITLE
Disable TraceEnvironmentPostProcessor

### ISSUE THREAD

**Issue by lldata** [spring-cloud/spring-cloud-sleuth#413]
Is it possible to disable TraceEnvironmentPostProcessor

I'd like to control my log format myself.

I think it is quite a hack, to override the log level
It introduces an unnecessary requirement to put the spring.application.name in bootstrap.yml
I'd rather not log the application name or the boolean on every line, until I really need it.

How can I disable the post processer from running? Or how can I override the results?

**Comment by marcingrzejszczak** [comment]
Unfortunately that's not possible since `TraceEnvironmentPostProcessor` is set before you can reach any properties. 

I understand that it can seem drastic to enforce a logging pattern but actually the benefits of having one, common way of logging is much greater than the unfortunate necessity to put a one line of entry inside your property. It's crucial to have standardization and I'm pretty sure that most people don't standardize the way their logging.

Of course you can still control your format by having the `logback-spring.xml`.

**Comment by lldata** [comment]
Even though I agree with your motivation, I still think your implementation is too heavy handed.
But I was able to work around the issue with logback-spring.xml.

For other developers who run into this problem:

I already have a logback-spring.xml file.

I copied this from https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml
`	<property name="FILE_LOG_PATTERN" value="%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"/>
`
Remove LOG_LEVEL_PATTERN.

**Comment by marcingrzejszczak** [comment]
I think we mentioned in the docs an approach with custom logback. How does your differ ?

**Comment by lldata** [comment]
I don't understand your question. I don't see any documentation on how you piggyback on LOG_LEVEL_PATTERN

I just wrote my workaround up, so Google can pick it up for other devs to find. :=)

**Comment by marcingrzejszczak** [comment]
Hmm I think I misunderstood what you're doing. You don't want to reuse that at all, I get it. http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_adding_to_the_project <-- just above this we're explaining how to reuse the pattern. Anyways thanks for pointing it out here. For sure it will be useful for someone!
