### ISSUE TITLE
Using Sleuth with Spring Cloud Stream removes read-only message headers id and timestamp

### ISSUE THREAD

**Issue by joaquinxxi** [spring-cloud/spring-cloud-sleuth#541]
I have managed to debug the code of my application using Spring Cloud Sleuth and Spring Cloud Stream, and found that it seems that the ID and TIMESTAMP generated on the request message are being removed by the (Integration)TraceChannelInterceptor.preSend() method (https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptor.java#L72) that adds the span to the message.

The problem seems to be that when creating the messageBuilder from the message (https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptor.java#L73) and copying only the non read-only headers (https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptor.java#L86), the messageId and Timestamp are not present in the generated GenericMessage anymore.

**Comment by marcingrzejszczak** [comment]
Hi! Why does it matter to you if we regenerate these values? What kind of a problem does it cause you? Cc @abilan

**Comment by artembilan** [comment]
@joaquinxxi ,

Please, share with us which Spring Cloud Sleuth version do you use?

My tests demonstrate that the `id` is there because message becomes *mutable* after interceptor.
The `timestamp` isn't there because `MessageHeaderAccessor` doesn't support it by default.
You should use a custom interceptor after `TraceChannelInterceptor` in the stack to create a new `Message` to let the new `id` and `timestamp` be populated.

Our intention in the `TraceChannelInterceptor` is really to have message *mutable* for further modifications. Therefore `id` and `timestamp` won't be present there afterward.
Any way, bare in mind: the message is *immutable* object and any new stable instance has its own `id` and particular `timestamp` of creation.

Hope that is clear.

**Comment by joaquinxxi** [comment]
Hi,

I don't mind if the message id and timestamp values are regenerated. These values are used by a non spring cloud stream application for tracking purposes. The problem was that they were not even regenerated, but contained null. I will try to follow the approach suggested by @artembilan and create a custom interceptor that will populate these values.

BTW, I am using Spring Cloud Sleuth 1.1.2.RELEASE.

**Comment by artembilan** [comment]
Great! As I said: we can't change that logic in the `TraceChannelInterceptor` because our intention to let message to be mutable afterwards. But I agree that we have there some flaws which should be fixed.

Only solution for your now and afterwards is a new interceptor to build fresh message from the incoming `payload` and `headers`:

```
public Message<?> preSend(Message<?> message, MessageChannel channel) {
	return MessageBuilder.createMessage(message.getPaylaod(), message.getHeaders());
}
```

**Comment by joaquinxxi** [comment]
Yep. That's what I did and it seems to work on message send.

However, even when I see that the message contains now the ID and TIMESTAMP that my interceptor adds before calling the AbstractMessageChannel.doSend(), these values are not sent to my rabbitmq (I cannot see them in the tcpdump I generated while sending the message), but the other custom headers are. Anyway, this is not spring-cloud-sleuth anymore, but spring-cloud-stream. I will ask in that project's gitter about it.

Thanks,
Joaquin.

**Comment by artembilan** [comment]
Good. But I think that is correct that nor `ID`, neither `TIMESTAMP` are transferred to RabbitMQ (or any other target protocol) - `AbstractHeaderMapper`: 
```
private static final Collection<String> TRANSIENT_HEADER_NAMES = Arrays.asList(
		MessageHeaders.ID, MessageHeaders.TIMESTAMP);
```
So, if you would like to transfer them as well, you have to re-map them to other custom headers.

**Comment by joaquinxxi** [comment]
Ok. Thank you. I will check if the other app can switch from reading the ID and TIMESTAMP headers they are reading to our custom headers.

**Comment by marcingrzejszczak** [comment]
@joaquinxxi any luck with checking your stuff?

**Comment by joaquinxxi** [comment]
As I mentioned the other application will be changed to read our custom headers instead of the standard ID and TIMESTAMP ones.
