### ISSUE TITLE
Elasticsearch Rest client - TraceId & spanId is not coming in logs 

### ISSUE THREAD

**Issue by aj070** [spring-cloud/spring-cloud-sleuth#554]
I'm using elasticsearch rest client and the traceId/spanId is not getting passed in the logs. But the app name is coming correctly. Is it the desired behaviour for all the third party logs. If so, what is the work around

**Comment by marcingrzejszczak** [comment]
Can you present some sample setup and code? I have no idea what the `Elasticsearch Rest client` is. If that's some 3rd party client to communicate with Elasticsearch via REST then no wonder it doesn't work. You need to take care of passing the tracing headers.

**Comment by aj070** [comment]
I'm using the client from elastic https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/index.html

If this won't work by default, can you provide me any insights on how to make it work? Some example links are good enough (I know this is not an "issue" to be raised in github if it is designed for not supporting this by default)

**Comment by marcingrzejszczak** [comment]
Sorry for the delay - I was sick :/

Anyways you can follow the instructions from the docs http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_custom_sa_tag_in_zipkin . Since `elasticsearch` is not traced as such you can treat it as an external service. That way when creating a span you can provide some custom tags and they will be read by Zipkin properly.

**Comment by aj070** [comment]
Thanks marcingrzejszczak.. And sorry for the delay :D
