### ISSUE TITLE
Difference between using Zipkin via Spring Cloud Stream and Zipkin Collector.

### ISSUE THREAD

**Issue by volijaadu** [spring-cloud/spring-cloud-sleuth#643]
I have started using Sleuth/Zipkin with Http.

Out of different ways to add slueth/zipkin from docs,  I am clear on the first two.

I am not clear on the use case /scenario for the remaining options.

- Sleuth with Zipkin via Spring Cloud Stream and
- Spring Cloud Sleuth Stream Zipkin Collector

 I believe both the above options use a messaging layer to send the traces to Zipkin. But, not sure of the difference.

Can you please provide me with the details on when to use them.

**Comment by marcingrzejszczak** [comment]
`Sleuth with Zipkin via Spring Cloud Stream` - this is the "client" of the message based communication. It knows how to send spans as messages to `Spring Cloud Sleuth Stream Zipkin Collector`.

`Spring Cloud Sleuth Stream Zipkin Collector` - this is the Zipkin collector. It means that you need this application to listen to spans and store them. It's using Stream to collect messages. So instead of sending spans via HTTP you'll send them via messaging.

Does it make sense now?

**Comment by volijaadu** [comment]
I assume you are referring to the fact that we need a Zipkin Server component to receive the streamed trace messages and a client to send them. 

The dependencies for "Spring Cloud Sleuth Stream Zipkin Collector" as provided in the docs ,  are what we need for Zipkin Server component to receive the traces sent and the "Sleuth with Zipkin via Spring Cloud Stream" dependencies are  for the client which will be sending the traces.

I added the dependencies along with the "@EnableZipkinStreamServer" annotation and built and started the Zipkin Server.

When I accessed the url, http://localhost:9411/ , I see a 404 "whitelabel error page".

Can you please help me on this.

**Comment by marcingrzejszczak** [comment]
http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.2.1.RELEASE/#_zipkin_consumer did you add the UI dependency as described in the documentation?

**Comment by volijaadu** [comment]
When I added the required UI dependencies as mentioned in docs, I was able to see the Zipkin UI page. Thanks for your help on this.

**Comment by marcingrzejszczak** [comment]
Always read the documentation :)
