### ISSUE TITLE
Support Spring HATEOAS Traverson HTTP client

### ISSUE THREAD

**Issue by shakuzen** [spring-cloud/spring-cloud-sleuth#671]
Currently, `RestTemplate` and `WebClient` are instrumented for tracing HTTP calls. It would be nice if calls made using the [Spring HATEOAS `Traverson` client](http://docs.spring.io/spring-hateoas/docs/current/reference/html/#client.traverson) were also traced out-of-the-box.

**Comment by marcingrzejszczak** [comment]
Just had a chat with @olivergierke and it turns out that the best way to instrument `Traverson` is to inject a `RestTemplate` bean into it. If you do that then the `RestTemplate` bean gets already instrumented and there's nothing else you need to do. You can call the `Traverson#setRestOperations` method to set the `RestTemplate` bean. Is that ok?

**Comment by shakuzen** [comment]
I think that could be fine. Maybe some documentation for it would be nice though. So people using Traverson would know how to do this when using Sleuth, since Spring HATEOAS is a Spring library.
