### ISSUE TITLE
Trace database calls through Spring Data integration

### ISSUE THREAD

**Issue by embs** [spring-cloud/spring-cloud-sleuth#788]
Main idea here is providing a db/db-driver agnostic instrumentation for tracing database calls within projects that access databases through Spring Data projects.

Related to #693

**Comment by marcingrzejszczak** [comment]
Why not just use https://github.com/gavlyukovskiy/spring-boot-data-source-decorator ?

**Comment by embs** [comment]
@marcingrzejszczak because, AFAIK, it is JDBC-specific. I couldn't, for instance, tracing db calls that happen through mongodb-driver.

**Comment by marcingrzejszczak** [comment]
So you can use the annotations and annotate your Spring Data interfaces

**Comment by embs** [comment]
I've tried them but couldn't annotate the spans with the info I'd like to (i.e. `db.instance`, `db.type`) as they seem to support tag spans from method's parameters only.

We could work on broadening their functionality but I think that, wrt system tracing, it'd be very nice if Sleuth treated database calls as first-class citizens -- just like calls to external web services. It seems to me that Spring Data provides us all we need to do it.

Does it sound like a bad idea, @marcingrzejszczak?

**Comment by embs** [comment]
@adriancole 

- by proposed do you mean the https://github.com/opentracing/specification project?
- are you aware of any ongoing discussions / works about database calls instrumentation in brave?

Accomplishing this through brave seems nice but I guess there is still a long road till brave implementation and sleuth transition to brave. On the other hand, Spring projects integration seems a rather tangible (although limited) solution.

**Comment by adriancole** [comment]
@embs I was talking about zipkin in that sentence. Brave currently has [3 database instrumentations upstream](https://github.com/openzipkin/brave/tree/master/instrumentation) (zipkin-js also has one for postgresql). Notably, we don't add modules without multiple parties involved, so the fact that there are several means there is experience there.

The reason I mention that we are likely to align with X-Ray is that they have made good choices. Upon request from us and others, they've also [open sourced their SDK](https://github.com/aws/aws-xray-sdk-java). The tagging policy there is a good place to start with, to broaden what's only "sql.query" in zipkin today.

On the road ahead, the more added now the harder it is to ever move the project. Meanwhile, we are in the middle of a lot of things including preparation for Spring Boot 2.0, the annual conference etc. Please have patience because putting together a good implementation is worth the wait, and the wait is mostly about a busy time of year. In the mean time, you can gather experience by looking at others and creating your own instrumentation. This can help later as well.

**Comment by marcingrzejszczak** [comment]
With Brave stuff done (#711) you can use py6spy https://github.com/openzipkin/brave/tree/master/instrumentation/p6spy to instrument all the database calls.

**Comment by embs** [comment]
Istio has a feature for [collection TCP interactions data](https://istio.io/docs/tasks/telemetry/tcp-metrics.html) which may also be valuable for tracing interactions with database services.
