### ISSUE TITLE
How does Zipkin use Oracle to save the data?

### ISSUE THREAD

**Issue by hibicus8888** [spring-cloud/spring-cloud-sleuth#827]
I want to use oracle to save zipkin date.On the Internet I only see the use of Mysql to save the data, Oracle can not be used to save Zipkin data?

**Comment by adriancole** [comment]
the mysql option is not meant for larger installations as the schema isn't
efficient. The other problem is that it uses MySQL dialect of SQL. I don't
think Oracle would work.
If testing oracle implies licensed software, it isn't likely to become
supported (because we won't be able to test it easily in open source)

**Comment by marcingrzejszczak** [comment]
It's more of a Zipkin than Sleuth question.
