### ISSUE TITLE
[Question] timestamps in different zones

### ISSUE THREAD

**Issue by jo2** [spring-cloud/spring-cloud-sleuth#868]
During a talk at Devoxx 2016 in Poland by Marcin Grzejszczak a question was asked if the timestamps are derived from the server time or a global time because there would be some problems if it is done with the server time and the servers are located in different time zones.

It was suggested to use a tool for synchronizing the time from which the timestamps are derived and it was also said that such a feature would be implemented. 

I couldn´t find an issue relating to that topic so I´d like to know if something like this is already implemented or if it is still on the todo list or if there is a workaround.

**Comment by marcingrzejszczak** [comment]
An issue is still there - https://github.com/spring-cloud/spring-cloud-sleuth/issues/275 . The workaround (or actually good practice) is to use NTP (https://en.wikipedia.org/wiki/Network_Time_Protocol) but I'm no expert on this topic. Maybe @wybczu can elaborate more on this?

**Comment by wybczu** [comment]
UNIX timestamp is defined as the number of seconds (or milliseconds) that have passed since the beginning of 1 January 1970, 00:00:00 UTC so it is timezone independent. However I would recommend using one timezone across your fleet, e.g. UTC. It will save you a lot of hassle with time calculations :)

As @marcingrzejszczak wrote, clock synchronization across your servers is a good practice or even a requirement in this case (not timezone specific) as you need to order events based on timestamps.

**Comment by jo2** [comment]
thank you for that information

**Comment by marcingrzejszczak** [comment]
No problem. Thanks @wybczu !
