### ISSUE TITLE
Missing client side Span

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-sleuth#875]
```
@NewSpan("busyWork")
public void busyWork() {
	LOGGER.info("starting busy work");
	for (int i = 0; i < 3; i++) {
		this.restTemplate.getForObject("http://localhost:8080/meet", String.class);
	}
	LOGGER.info("finished busy work");
}
```

This block seems to generate a busyWork Span w/o Kind, and a server side span for the `/meet` endpoint, but seems to miss the client side Span.

In pre-Seluth 2.0.0.M6, client side span was determined by inspecting Sleuth logs for cr/cs entries.

Sample code based on https://github.com/spring-cloud/spring-cloud-gcp/pull/438

**Comment by marcingrzejszczak** [comment]
It was related to the fact that the app was calling itself and Brave doesn't like such cases. Due to this only server side instrumentation was present.

**Comment by clupeids** [comment]
@marcingrzejszczak This is still an issue with 2.0.0.RC1.  

> It was related to the fact that the app was calling itself and Brave doesn't like such cases. Due to this only server side instrumentation was present.

It appears that the issue is related to how the Sleuth configures the TracingClientHttpRequestInterceptor and the HttpServerHandler.  If a single Recorder instance is used for both client and Server (by reusing a httpTracing instance) then span created by the HttpServerHandler will overwrite the span created by the TracingClientHttpRequestInterceptor.

**Comment by clupeids** [comment]
@marcingrzejszczak I'm referring to the issue initially raised by saturnism at the top of the thread.  

The issue is: when an application calls back to itself via restTemplate only the server span is reported and the client span is lost.

**Comment by marcingrzejszczak** [comment]
Brave was never intended to work like i this cc @adriancole

**Comment by clupeids** [comment]
> Brave was never intended to work like i this cc @adriancole

@marcingrzejszczak As far as I can see this is due to how sleuth is using Brave rather than a brave limitation.

In TraceAutoConfiguration, a single Tracing bean is created, then used for both the client **and** the server (i.e in TraceWebClientAutoConfiguration).  If a second tracing bean is created for the TracingClientHttpRequestInterceptor both the client and server spans are created and reported correctly.

**Comment by marcingrzejszczak** [comment]
So maybe file an issue in Brave?

**Comment by clupeids** [comment]
@marcingrzejszczak Thanks for your comments.  I will wait for Adrian to comment.

> Since you're using Spring Boot you are free to introduce 2 beans and do whatever you want with them.

Yes, I can work around this issue by excluding TraceWebClientAutoConfiguration and providing custom interceptors.

> What if you want to get the Tracer via static call? It won't work.

Yes that could be a problem, if you didn't know which tracer you were after.  However unless brave change how a span is identified, collecting the server and client spans in the one tracer will always cause one to merge/overwrite the other (given the same trace/span id).

> I think the way you want to use it is extremely custom.

Possibly...  Anecdotally, it is quite common, especially with multiple instances of stateless services hosted behind a load balancer. Saturnism appears to have seen this too.  However 2 data points is not a trend.
