### ISSUE TITLE
http status?

### ISSUE THREAD

**Issue by jmart1** [spring-cloud/spring-cloud-sleuth#882]
In past teams I have worked on we always seemed to find existing tracing tools lacking.  Specifically we required one log msg at the end of a request that contained the HTTP status, latency, inbound msg, outbound response, HTTP path (with templated path params, e.g. /some/rest/path/{id} ), trace/span/parent_span ID's, HTTP method, and app name.

As such we have always had to roll our own solution.  Is there a way to add HTTP status, inbound msg, outbound response, path with templated path params, app name, and parent_span ID to Spring Sleuth?  With all this data we were able to easily troubleshoot issues quickly.

**Comment by marcingrzejszczak** [comment]
Can you describe what you mean by:

> Is there a way to add HTTP status, inbound msg, outbound response, path with templated path params, app name, and parent_span ID to Spring Sleuth? 

With the 2.0 version and Brave support you can provide your own bean of `HttpTracing` and log whatever message you want whenever an HTTP span is created. 

Example for the legacy Sleuth approach with Brave: https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceHttpAutoConfiguration.java#L53-L62

Here you can log whatever you want:

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthHttpServerParser.java#L62-L80

**Comment by jmart1** [comment]
> Can you describe what you mean by:
> Is there a way to add HTTP status, inbound msg, outbound response, path with templated path
> params, app name, and parent_span ID to Spring Sleuth?

So we use ELK.  It is important that all the items are provided on the same log msg... similar to having it all on the same row in a DB.  So when Spring Sleuth sends log message to ELK it would need to have all those items.

>  With the 2.0 version and Brave support you can provide your own bean of HttpTracing and log whatever message you want whenever an HTTP span is created.

Hey pretty cool.  The HTTP status, and response, and latency need to be logged at the end of a request.  And they need to be added to the same log msg that was mentioned in my paragraph.  So can we use HttpTracing to decorate the one final log msg with that missing items?

>  Here you can log whatever you want:
>  https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthHttpServerParser.java#L62-L80

This looks promising.  Its funny how it has the check for 200 OK and error != null cause I remember having to write that same code in the custom Servlet Filter to accomplish same.

Would it be possible to have a few days to process and test this out before closing the issue?

**Comment by adriancole** [comment]
The default data policy can be overridden to include response code always.

Why are you replicating so much span data in elasticsearch vs just sending
zipkin data there and correlating the rest with trace and span ID?

On 5 Mar 2018 6:09 am, "Jose Martinez" <notifications@github.com> wrote:

Can you describe what you mean by:
Is there a way to add HTTP status, inbound msg, outbound response, path
with templated path
params, app name, and parent_span ID to Spring Sleuth?

So we use ELK. It is important that all the items are provided on the same
log msg... similar to having it all on the same row in a DB. So when Spring
Sleuth sends log message to ELK it would need to have all those items.

With the 2.0 version and Brave support you can provide your own bean of
HttpTracing and log whatever message you want whenever an HTTP span is
created.

Hey pretty cool. The HTTP status, and response, and latency need to be
logged at the end of a request. And they need to be added to the same log
msg that was mentioned in my paragraph. So can we use HttpTracing to
decorate the one final log msg with that missing items?

Here you can log whatever you want:
https://github.com/spring-cloud/spring-cloud-sleuth/
blob/master/spring-cloud-sleuth-core/src/main/java/org/
springframework/cloud/sleuth/instrument/web/SleuthHttpServerParser.java#
L62-L80

This looks promising. Its funny how it has the check for 200 OK and error
!= null cause I remember having to write that same code in the custom
Servlet Filter to accomplish same.

Would it be possible to have a few days to process and test this out before
closing the issue?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/spring-cloud/spring-cloud-sleuth/issues/882#issuecomment-370268868>,
or mute the thread

**Comment by marcingrzejszczak** [comment]
Ping @jmart1 ?

**Comment by jmart1** [comment]
> Why are you replicating so much span data in elasticsearch vs just sending
zipkin data there and correlating the rest with trace and span ID?

So we like to send data to ElasticSearch (ES) so that it can then be queried, graphed, trended, monitored, reported, etc.  We do all of the above based on HTTP status, API, application, latency.  We also need the request bodies and response bodies of everything coming in and out.  By having all this data on one ES entry, it makes very easy to troubleshoot.  As you know ES has amazing and powerful querying features, especially when used with Kibana.

I am working right now on following the steps detailed int he links that @marcingrzejszczak  provided.

**Comment by jmart1** [comment]
How exactly am I suppose to get my own HttpServerParser implementation to get used?  I noticed that TraceHttpAutoConfiguration.httpTracing() is conditional on missing.  So does that mean if I add my own HttpTracing that TraceHttpAutoConfiguration.httpTracing() will not get executed?

I tried creating my own SleuthHttpServerParser impl and putting it into the Spring context, but it was not taken up by TraceHttpAutoConfiguration.  My apologies for not getting it.  It seems like what I want to do, send the tracing information with HTTP access information to Elastic (via logback/logstash encoder), should be doable.

**Comment by jmart1** [comment]
So I went ahead and added my own HttpTracing to the Spring context.  And as I suspected that one from TraceHttpAutoConfiguration is no longer in the Spring context and not being used... so my traces do not show up in Zipkin.

 ```
   @Bean
    HttpTracing httpTracing(Tracing tracing) {
        return HttpTracing.newBuilder(tracing)
                .serverParser(serverParser)
                .build();
    }
```

**Comment by jmart1** [comment]
I take it back.  I was able to add my own HttpTracing and implement my own HttpServerParser.  Matt, thank you for the help!  And thank you for all the amazing code you wrote for this project.... we rely on it.

**Comment by adriancole** [comment]
Ps next milestone you can just provide a bean for the parser instead of
overriding everything. This was also needed for GCP
