### ISSUE TITLE
@EnableZipkinServer is not found in the path  'zipkin.server.EnableZipkinServer' with the version of M9

### ISSUE THREAD

**Issue by godpit** [spring-cloud/spring-cloud-sleuth#915]
<dependency>
			<groupId>io.zipkin.java</groupId>
			<artifactId>zipkin-server</artifactId>
		</dependency>
		<dependency>
			<groupId>io.zipkin.java</groupId>
			<artifactId>zipkin-autoconfigure-ui</artifactId>
			<scope>runtime</scope>
		</dependency>
these are not Existing.

**Comment by adriancole** [comment]
As of sleuth 2.x there are no extensions to zipkin server anymore. Starting
with 1.3, for example, you can use standard zipkin for rabbit mq transport
etc.

http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.2.RELEASE/single/spring-cloud-sleuth.html#_sleuth_with_zipkin_via_rabbitmq_or_kafka

As sleuth is a client, there's no reason for it to claim a dependency on
zipkin-server. That's why you are not seeing it.

**Comment by godpit** [comment]
in the before,i used @EnableZipkinServer, but now it doesn't work well.so , what can i  do to repair it?

**Comment by godpit** [comment]
I used it as monitor server.

**Comment by godpit** [comment]
however, i use the '<dependency>
			<groupId>org.springframework.amqp</groupId>
			<artifactId>spring-rabbit</artifactId>
		</dependency>' ,but it didn't work well.

**Comment by adriancole** [comment]
You can join https://gitter.im/spring-cloud/spring-cloud-sleuth for
troubleshooting. There is no action to take here.
