### ISSUE TITLE
zipkin does not shows ui when accessing thru gateway

### ISSUE THREAD

**Issue by momentum123** [spring-cloud/spring-cloud-sleuth#941]
hi @marcingrzejszczak  !!!
when I access zipkin thru localhost:9411 it works fine but when I access it thru gateway
https://localhost:443/zipkin it shows up a blank 
attached images for both cases :

[case1](https://drive.google.com/file/d/1koK5nJfo2RAOy7PFN0vfqoSEcDu4_Nxl/view?usp=sharing)

[case2](https://drive.google.com/file/d/1Zx6ze9l3XAEOdubdHKuSBXQLrmGUMTPg/view?usp=sharing)

**Comment by marcingrzejszczak** [comment]
Hi! You're asking a question in the Sleuth repo about Zipkin. I don't know if that's what you wanted.

When you file an issue there is this comment:

> Bug report
> Please provide details of the problem, including the version of Spring Cloud that you
> are using. If possible, please provide a test case or sample application that reproduces
> the problem. This makes it much easier for us to diagnose the problem and to verify that
> we have fixed

You haven't provided a single useful information in your file report. Also, you've provided links to 2 screenshots that tell me absolutely nothing. Can you please provide any useful details following the guidelines above? Otherwise I will have to close this issue.
