### ISSUE TITLE
How to provide custom Sender?

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-sleuth#960]
I noticed that the `Sender` implementation is selected from:
https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/ZipkinSenderConfigurationImportSelector.java

How should we extend Zipkin autoconfiguration with a different Sender, like `StackdriverSender`? :)
https://github.com/openzipkin/zipkin-gcp/tree/master/sender-stackdriver

/cc @joaoandremartins @marcingrzejszczak @adriancole

**Comment by adriancole** [comment]
kindof beg to differ on this one. we have a lot of "senders" out
there, and unlikely we'll want people to copy/paste properties etc.

in the case of gcp it would be BytesEncoder<Span> (we already have
this) and also Sender due to the custom encoder for stackdriver

I just double-tested this.. it works

https://github.com/openzipkin/sleuth-webmvc-example/compare/use-stackdriver-sender

I'll add a link to the instructions on the main README once we bump to
zipkin 2.8 based dependencies. proto changes ever so mildly until
then.

**Comment by marcingrzejszczak** [comment]
Ooops. Don't listen to me then ;) @adriancole is much smarter, you should listen to him @saturnism :)
